export default {
    name: "thought",
    cards: [
        ["\\lim_{n\\to\\infty}\\frac{2^n}{n!}", "0<\\frac{2^n}{n!}=\\frac{2*2*2*...*2}{1*2*3*...*n}\\le\\frac{4}{n} \\\\ n\\to\\infty, 两边都为0 \\\\ 解法2: a_n = \\frac{2^n}{n!}, a_{n+1} = \\frac{2}{n+1}a_n \\\\ 单调有界函数\\to有极限,假设\\lim_{n\\to\\infty}a_n = A \\\\ 两边取极限 A=0*A, A=0"],
        ["x\\to 0时,\\frac{1}{x^2}\\sin\\frac{1}{x}是无穷大吗", "令a=\\frac{1}{2n\\pi+\\frac{\\pi}{2}}, 使得代入后\\sin\\frac{1}{x}=1 \\\\ 令b=\\frac{1}{2n\\pi}, 使得代入后\\sin\\frac{1}{x}=0 \\\\  则对于任意的M>0,都有\\delta>0 \\\\ 0<a<\\delta 和 0<b<\\delta \\\\ 代入a = (2n\\pi+\\frac{\\pi}{2})^2>M, 代入b得0 \\\\ 所以是无界的，但不是无穷大"],
        ["\\lim_{x\\to\\infty}(\\frac{x^2}{(x-a)(x+b)})^x的思路?", "原式变为\\lim_{x\\to\\infty}(\\frac{x}{x-a})^x(\\frac{x}{x+b})^x \\\\ \\lim_{x\\to\\infty}\\frac{1}{(1-\\frac{a}{x})^x}\\frac{1}{(1+\\frac{b}{x})^x} = e^{a-b} "],
        ["\\lim_{n\\to\\infty}\\frac{n^{n+1}}{(n+1)^n}\\sin\\frac{1}{n}的思路?", "原式变为(\\frac{n}{n+1})^n n\\sin\\frac{1}{n} \\\\ n\\to\\infty, \\frac{1}{n}\\to 0, 等价代换后n\\sin\\frac{1}{n}=1 \\\\ 左边上下除n得\\frac{1}{(1+\\frac{1}{n})^n} \\\\ 极限值为 e^{-1}"],
        ["\\lim_{x\\to 0}\\frac{\\ln(\\cos x)}{x^2}=?", "\\frac{0}{0}型第一反应用洛必达 \\\\ 得\\lim_{x\\to 0}\\frac{-\\tan x}{2x}, 还是\\frac{0}{0}, 再洛? \\\\ 这一步就可以用无穷小代换, \\tan x \\sim x \\\\ 极限值为-\\frac{1}{2}, 所以不要一条路洛到底 \\\\ 要灵活应用, 这题也可以写成 \\ln(1+\\cos x - 1) \\\\ 等价代换为 -(1-\\cos x),再换-\\frac{1}{2}x^2"],
        ["\\lim_{x\\to 0}\\frac{\\sqrt{1+f(x)\\sin(2x)}-1}{e^{3x}-1}=2 \\\\ 那么\\lim_{x\\to 0}f(x)=?", "这道题的思路是等价无穷小代换 \\\\ 分母可以用 e^x-1 \\sim x \\\\ 看似分子也可以用 (1+x)^a-1 \\sim ax \\\\ 但使用前需要确定f(x)\\sin(2x) \\to 0 \\\\ 若极限的商存在，且分母\\to0,那分子也\\to 0 \\\\ 所以 \\lim_{x\\to0}\\frac{\\frac{1}{2}f(x)2x}{3x}=2, f(x)=6"],
        ["\\lim_{x\\to0}\\frac{\\arcsin x-\\sin x}{\\arctan x-\\tan x}思路", "减法想等价代换需要两边比值不为1 \\\\ \\arcsin x \\sim x, \\sin x \\sim x, 比值为1,没法直接换 \\\\ 但可以加上x变成 \\lim_{x\\to0}\\frac{(\\arcsin x -x)-(\\sin x-x)}{(\\arctan x-x)-(\\tan x-x)} \\\\ \\arcsin x-x \\sim \\frac{1}{6}x^3, \\sin x-x \\sim -\\frac{1}{6}x^3 \\\\ \\arctan x-x \\sim -\\frac{1}{3}x^3, \\tan x-x \\sim \\frac{1}{3}x^3 \\\\ 两边比值不为1,可以等价代换"],
        ["\\lim _{x\\to 0}\\frac{x-\\ln \\left(1+\\tan x\\right)}{x^2}思路", "已知x-\\ln \\left(1+x\\right)\\sim \\frac{1}{2}x^2 \\\\ 但此时外面是x里面是\\tan x,不能直接换 \\\\ 我们可以两边同时减去\\tan x \\\\ \\lim _{x\\to 0}\\frac{\\left(x-\\tan x\\right)-\\left[\\ln \\left(1+\\tan x\\right)-\\tan x\\right]}{x^2} \\\\ x-\\tan x\\sim -\\frac{1}{3}x^3, \\ln\\left(1+\\tan x\\right)-\\tan x\\sim-\\frac{1}{2}\\tan^{2}x \\\\ 减法两边比值不为1,可以等价代换"],
        ["若\\lim f(x)g(x)存在 \\\\ 且\\lim f(x)\\to\\infty \\\\ 证明\\lim g(x)\\to0", "\\lim f\\left(x\\right)g\\left(x\\right)=A \\\\ \\lim g\\left(x\\right)=\\lim \\left(\\frac{f\\left(x\\right)g\\left(x\\right)}{f\\left(x\\right)}\\right) \\\\ \\lim f(x)g(x) 趋向有限值, f(x)趋向无穷 \\\\ \\therefore \\lim g(x)\\to0"],
        ["\\lim _{x\\to 0}\\left[\\frac{1}{x}-\\left(\\frac{1}{x}-a\\right)e^x\\right]=1 \\\\ 求a思路?", "对于知道极限求参数的题，先找到存在的项提出来 \\\\ 原式= \\lim _{x\\to 0}\\left(\\frac{1-e^x}{x}\\right)+a\\lim _{x\\to 0}e^x=1 \\\\ a\\lim _{x\\to 0}e^x这项是存在的,原式的极限也是存在的 \\\\ 所以剩下的项的极限也是存在的 \\\\ 等价代换后得a=2"],
        ["\\lim _{x\\to 0}\\frac{\\sin x}{e^x-a}\\left(\\cos x-b\\right)=5, \\\\ 求a,b", "\\lim _{x\\to 0}\\frac{\\sin x\\left(\\cos x-b\\right)}{e^x-a}=5,分子趋向0 \\\\ 极限存在且不为0,那分母就一定趋向0 \\\\ \\lim_{x\\to0}e^x-a=0, 得a=1, 代入原式 \\\\ \\lim _{x\\to 0}\\frac{\\sin x\\left(\\cos x-b\\right)}{e^x-1}=5 等价代换 \\\\ \\lim _{x\\to 0}\\left(\\cos x-b\\right)=5,得b=-4 "],
        ["\\lim _{x\\to 1}\\left(1-x^2\\right)\\tan \\left(\\frac{\\pi }{2}x\\right) 的巧算", "原式=\\lim _{x\\to 1}\\left(1-x\\right)\\left(1+x\\right)\\frac{\\sin \\left(\\frac{\\pi }{2}x\\right)}{\\cos \\left(\\frac{\\pi }{2}x\\right)} \\\\ 其中(1+x)和\\sin \\frac{\\pi}{2}x是非零的因子，可以先算 \\\\ 原式=2\\lim _{x\\to 1}\\frac{\\left(1-x\\right)}{\\cos \\left(\\frac{\\pi }{2}x\\right)}, 洛必达就很方便了 \\\\ 极限值为\\frac{4}{\\pi}"],
        ["\\lim _{x\\to 0}\\frac{\\ln \\left(1+x\\right)-\\left(ax+bx^2\\right)}{x^2}=2 \\\\ 求a,b的思路","用泰勒替换\\ln(1+x),展开到2次即可(分母) \\\\ \\ln(1+x)=x-\\frac{x^2}{2}+o(x^2) \\\\ 整理后: \\lim _{x\\to 0}\\frac{\\left(1-a\\right)x-\\left(\\frac{1}{2}+b\\right)x^2+o\\left(x^2\\right)}{x^2}=2 \\\\ 极限值是存在的=2,\\frac{\\left(1-a\\right)x}{x^2}的极限是无穷 \\\\ 所以(1-a)要为0,把式子中的无穷去掉, a=1 \\\\ \\frac{o\\left(x^2\\right)}{x^2}=0, 所以-\\frac{\\left(\\frac{1}{2}+b\\right)x^2}{x^2}=2, b=-\\frac{5}{2}"],
        ["\\lim _{x\\to 0}\\frac{\\cos x-e^{-\\frac{x^2}{2}}}{x^4} 思路","洛必达和等价代换不太好做,用泰勒 \\\\ 分母是4次,所以展开到4次就行 \\\\ \\cos x=1-\\frac{x^2}{2}+\\frac{x^4}{24}+o\\left(x^4\\right) \\\\ e^{-\\frac{x^2}{2}}=1+\\left(-\\frac{x^2}{2}\\right)+\\left(-\\frac{x^2}{2}\\right)^2+o\\left(x^4\\right) \\\\ 代入原式后分子剩下 -\\frac{1}{12}+o(x^4) \\\\ 两个o(x^4)形式一样，真实值不同, 所以没被消掉 \\\\ 最后极限值为: -\\frac{1}{12}"],
        ["证明1-\\cos^\\alpha(x) \\sim  \\frac{\\alpha}{2}x^2","1-\\cos^\\alpha(x) \\sim \\frac{\\alpha}{2}x^2 \\\\ 证: 1-\\cos ^{\\alpha }x=1-\\left(1+\\cos x-1\\right)^{\\alpha } \\\\ =-\\left(\\left(1+\\cos x-1\\right)^{\\alpha }-1\\right) \\\\ \\sim -\\alpha \\left(\\cos x-1\\right) \\\\ \\sim -\\alpha \\cdot -\\frac{1}{2}x^2 = \\frac{\\alpha }{2}x^2"],
        ["n\\to\\infty时，\\left(1+\\frac{1}{n}\\right)^n-e \\sim \\frac{b}{n^a} \\\\ 求a,b","\\left(1+\\frac{1}{n}\\right)^n-e=e^{n\\ln \\left(1+\\frac{1}{n}\\right)}-e \\\\ =e\\left(e^{n\\ln \\left(1+\\frac{1}{n}\\right)-1}-1\\right) \\\\ \\sim e\\left(n\\ln \\left(1+\\frac{1}{n}\\right)-1\\right) \\\\ =en\\left(\\ln \\left(1+\\frac{1}{n}\\right)-\\frac{1}{n}\\right) \\\\ \\sim en\\left(-\\frac{1}{2}\\left(\\frac{1}{n}\\right)^2\\right) =-\\frac{e}{2n} \\\\ \\therefore a=1, b= -\\frac{e}{2n} "],
        ["f\\left(x\\right)=\\frac{\\ln \\left|x\\right|}{\\left|x-1\\right|}\\sin x \\\\ f(x)有几个间断点，它们分别是什么类型","x=0时,\\ln|x|没有意义 \\\\ \\lim _{x\\to \\ 0}\\frac{\\ln \\left|x\\right|}{\\left|x-1\\right|}\\sin x =\\lim _{x\\to \\ 0}\\ln \\left|x\\right|\\sin x \\\\ 0×\\infty,把\\sin x 等价代换后放到分母上 \\\\ =\\lim _{x\\to \\ 0}\\frac{\\ln \\left|x\\right|}{\\frac{1}{x}}=\\lim _{x\\to \\ 0}\\frac{\\frac{1}{x}}{-\\frac{1}{x^2}}=0 \\\\ 极限存在，所以x=0是一个可去间断点 \\\\ x=1时分母为0, 代入后\\sin(1)为非零因子，提出来 \\\\ =\\sin 1\\lim _{x\\to 1}\\frac{\\ln \\left(x\\right)}{\\left|x-1\\right|}=\\sin 1\\lim _{x\\to 1}\\frac{\\ln \\left(1+x-1\\right)}{\\left|x-1\\right|} \\\\ 等价代换 \\sin 1\\lim _{x\\to 1}\\frac{x-1}{\\left|x-1\\right|}, 左右极限分别为-1,1 \\\\ 左右极限不同，所以x=1是一个跳跃间断点"],
        ["讨论 f\\left(x\\right)=\\frac{x}{1-e^{\\frac{x}{1-x}}} 的连续性 \\\\ 并指出间断点类型","f(x)在x=1和x=0上没意义，是间断点 \\\\ 解:由于f(x)是初等函数，则除x=0,1时处处连续 \\\\ \\lim _{x\\to 0}\\frac{x}{-\\frac{x}{1-x}}=-1, x=0是可去间断点 \\\\ \\lim _{x\\to 1^-}\\frac{1}{1-\\infty }=0, \\lim _{x\\to 1^+}\\frac{1}{1-0}=1 \\\\ 左右极限存在但不同，所以是跳跃间断点 \\\\ e^{\\infty}要特别注意左右极限不同"],
        ["f\\left(x\\right)=\\lim _{n\\to \\infty }\\frac{1+x}{1+x^{2n}} \\\\ 找到f(x)的间断点","注意！这里f(x)是一个极限的形式 \\\\ 需要先求极限，把表达式写出来 \\\\ f\\left(x\\right)=1,x=1 \\\\ f\\left(x\\right)=1+x,\\left|x\\right|<1 \\\\ f\\left(x\\right)=0,\\left|x\\right|>1 \\\\ f\\left(x\\right)=0,x=-1"],
        ["f(x)在[a,b]上连续,a<c<d<b \\\\ 证明:对任意正数p,q,至少存在一个\\xi \\\\ 使pf\\left(c\\right)+qf\\left(d\\right)=\\left(p+q\\right)f\\left(\\xi \\right)", "题目其实是要证明:\\frac{pf\\left(c\\right)+qf\\left(d\\right)}{\\left(p+q\\right)}=f\\left(\\xi \\right) \\\\ 根据介值定理推论可知，只要等号左边介于最大值和最小值 \\\\ 等式就成立。如果f(c)和f(d)相等，p+q就能消掉 \\\\ 令f(c)和f(d)都等于[c,d]上的最大值M和最小值m \\\\ \\frac{\\left(p+q\\right)m}{\\left(p+q\\right)}\\le \\frac{pf\\left(c\\right)+qf\\left(d\\right)}{\\left(p+q\\right)}\\le \\frac{\\left(p+qf\\right)M}{\\left(p+q\\right)} \\\\ 关键要能看出题目与介值定理的关系,和如何放缩"],
        ["image:math_derivative_1.png", "在x_0处的导数，一定与f(x_0)的定义相关 \\\\ 题目中以及A和B选项中,都没说明f(0)的定义 \\\\ 但是又说x=0处可导，所以A,B一定错 \\\\ C,D都说x=0处可导,所以x=0处一定连续 \\\\ 因为连续,可从题干中\\lim_{x\\to0}f(x)=0得到f(0)=0 \\\\ f'\\left(0\\right)=\\lim _{x\\to 0}\\frac{f\\left(x\\right)}{x} 存在,分母趋向0,那分子也趋向0 \\\\ 能模糊感觉到f(x)是和x同阶或高阶无穷小 \\\\ 所以感觉C是正确的,要证明的话就上下同除x \\\\ \\lim _{x\\to 0}\\frac{f\\left(x\\right)/x}{\\sqrt{\\left|x\\right|}/x}=\\lim _{x\\to 0}\\frac{f\\left(x\\right)}{x}\\frac{x}{\\sqrt{\\left|x\\right|}}=0"],
        ["y=f(x)由y-x=e^{x(1-y)}确定 \\\\ \\lim_{n\\to\\infty}n(f(\\frac{1}{n})-1)=?", "1.类似这种f(x)没直接给的情况，代入特殊值看看 \\\\ 代入x=0,得y=1,即f(0)=1 \\\\ \\lim _{n\\to \\infty }n\\left(f\\left(\\frac{1}{n}\\right)-1\\right) = \\lim _{n\\to \\infty }\\frac{\\left(f\\left(\\frac{1}{n}\\right)-1\\right)}{\\frac{1}{n}} \\\\ 2. 要能看出来右边和f'(0)的定义很像 \\\\ 1=f(0),所以右边就是f'(0) \\\\ 3.对隐函数求导，只是求某个导数值的话，直接代入 \\\\ y'-1=e^{x\\left(1-y\\right)}\\left[\\left(1-y\\right)+x\\left(-y'\\right)\\right] \\\\ 代入(x=0,y=1), 可得到y'的值，也就是f'(0)的值"],
        ["f'\\left(x_0\\right)=-1 \\\\ \\lim _{x\\to 0}\\frac{x}{f\\left(x_0-2x\\right)-f\\left(x_0-x\\right)}=?", "这题的思路是把要求的极限，凑成导数的定义 \\\\ 用题目中已知的f'(x_0)=-1,求出极限值 \\\\ 第一个要点：没有的东西，可以+上再-去 \\\\ 导数的定义需要f(x_0),式中没有，所以加上减去 \\\\ \\lim _{x\\to 0}\\frac{f\\left(x_0-2x\\right)+f\\left(x_0\\right)-f\\left(x_0-x\\right)-f\\left(x_0\\right)}{x} \\\\ 第二个要点：导数的定义不拘泥于\\triangle x的形式 \\\\ \\lim _{x\\to 0}\\frac{f\\left(x_0-2x\\right)-f\\left(x_0\\right)}{2x}, \\triangle x 被换成了2x \\\\ 但它一样是f'(x_0)的定义!本题答案是1 \\\\ 如果是填空题，可找一个符合条件的真实函数 \\\\ 如：f(x)=-x,它的导数恒为-1 \\\\ 用这个f(x)代入到要求的极限，一样能得到答案为1"],
        ["x=\\sqrt{t^2+1} \\\\ y=\\ln \\left(t+\\sqrt{t^2+1}\\right) \\\\ 求 \\left.\\frac{d^2y}{dx^2}\\right\\vert_{t=1} ", "\\frac{dy}{dx}=\\frac{\\frac{1}{\\sqrt{1+t^2}}}{\\frac{2t}{2\\sqrt{t^2+1}}}=\\frac{1}{t} \\\\ 这一步一定要注意化简 \\\\ 否则又复杂又容易错 \\\\ 最终答案是-\\sqrt{2}"],
        ["\\lim _{h\\to 0}\\frac{\\cos \\sqrt{\\left|h\\right|}-1}{h}=?", "\\sqrt{|x|}\\to0, 原式=\\lim _{h\\to 0}\\frac{-\\frac{1}{2}\\left|h\\right|}{h} \\\\ 左极限为\\frac{1}{2}, 右极限为-\\frac{1}{2} "],
        ["求\\rho=e^\\theta在点(\\rho,\\theta)=(e^{\\frac{\\pi}{2}},\\frac{\\pi}{2}) \\\\ 处的切线的直角坐标方程", "x=\\rho\\cos\\theta, y=\\rho\\sin\\theta \\\\ 首先对参数方程求导 \\\\ \\frac{dy}{dx}=\\frac{e^{\\theta }\\sin \\theta +e^{\\theta }\\cos \\theta }{e^{\\theta }\\cos \\theta -e^{\\theta }\\sin \\theta } \\\\ 代入\\theta=\\frac{\\pi}{2}可得斜率为-1 \\\\ 再将\\theta代入参数方程求出x,y \\\\ 方程为: y+x=e^{\\frac{\\pi}{2}}"],
        [   "相关变化率解题思路 \\\\ 1.建立相关联式子的方程 \\\\ 2.求导、代入",
            "image:math_related_rate_problem_1.png",
            "变化率就是导数，所以\\frac{dx}{dt}=v_0 \\\\ 要求l对时间的变化率，就是求\\frac{dl}{dt} \\\\ l=\\sqrt{x^2+y^2}=\\sqrt{x^2+x^6} \\\\ \\frac{dl}{dt}=\\frac{2x\\cdot x'+6x^5\\cdot x'}{2\\sqrt{x^2+x^6}} \\\\ 代入x=1,得变化率为2\\sqrt{2}v_0"],

        ["\\lim _{x\\to 0}\\left(\\frac{\\sin 6x+xf\\left(x\\right)}{x^3}\\right)=0 \\\\ 那么\\lim _{x\\to 0}\\left(\\frac{6+f\\left(x\\right)}{x^2}\\right)=?",
            "解法1：\\pm6x凑要求的式子 \\\\ \\lim _{x\\to 0}\\left(\\frac{\\sin 6x-6x+xf\\left(x\\right)+6x}{x^3}\\right)=0 \\\\ \\lim _{x\\to 0}\\frac{\\sin 6x-6x}{x^3}+\\lim _{x\\to 0}\\frac{xf\\left(x\\right)+6x}{x^3}=0 \\\\ \\lim _{x\\to 0}\\frac{-\\frac{1}{6}\\left(6x\\right)^3}{x^3}+\\lim _{x\\to 0}\\frac{f\\left(x\\right)+6}{x^2}=0 \\\\ ans=36 ",
            "解法2: 泰勒展开 \\\\ \\lim _{x\\to 0}\\left(\\frac{6x-\\frac{\\left(6x\\right)^3}{6}+xf\\left(x\\right)}{x^3}\\right)=0 \\\\ \\lim _{x\\to 0}\\frac{6x+xf\\left(x\\right)}{x^3}-\\lim _{x\\to 0}\\frac{\\left(6x\\right)^3}{x^3}=0 \\\\ \\lim _{x\\to 0}\\frac{6+f\\left(x\\right)}{x^2}-36=0"
        ],

        ["image:math_extereme_value_problem_3.png",
            "0点的导数需要用定义去做 \\\\ f_+'\\left(0\\right)=\\lim _{x\\to 0^+}\\frac{x^{2x}-1}{x}=\\lim _{x\\to 0^+}\\frac{e^{2x\\ln \\left(x\\right)}-1}{x} \\\\ =\\lim _{x\\to 0^+}\\frac{2x\\ln \\left(x\\right)}{x}极限为\\infty,0点右导数不存在 \\\\ 仔细观察题干，0点的左导数就是\\left(x^{ex}+1\\right)'\\left(0\\right) \\\\ 不需要自己用定义算，可以节省时间 \\\\ 0点左右两边的导函数可以求出来，写好x范围",
            "x=0处导数不存在，所以可能是个极值点 \\\\ 观察导数后发现，0点左右导数值从正到负 \\\\ 貌似是一个极大值? 导数在x=0不存在\\\\ 一定要验证x=0处连续 \\\\ 就是证明：\\lim _{x\\to 0^+}x^{2x}=\\lim _{x\\to 0^-}xe^x+1 \\\\ \\lim _{x\\to 0^+}x^{2x}=\\lim _{x\\to 0^+}e^{2x\\ln \\left(x\\right)}=e^0=1 \\\\ x=0处连续,是个极大值"],

        [   "image:math_extereme_value_problem_2.png",
            "解法1:保号性 \\\\ \\lim _{x\\to 0}\\frac{f\\left(x\\right)}{1-\\cos x}=2>0 \\\\ 所以在x=0的某个去心邻域中 \\frac{f\\left(x\\right)}{1-\\cos x}>0 \\\\ 在去心邻域中 1-\\cos x >0, 所以 f(x)>0 \\\\ f(0)=0, 其去心邻域f(x)>f(0)=0 \\\\ 这就是极小值的定义",
            "解法2:找个函数 \\\\ \\lim _{x\\to 0}\\frac{f\\left(x\\right)}{1-\\cos x}=\\lim _{x\\to 0}\\frac{f\\left(x\\right)}{\\frac{1}{2}x^2}=2 \\\\ \\lim _{x\\to 0}\\frac{f\\left(x\\right)}{x^2}=1, 所以取f(x)=x^2 \\\\ 验证每个选项后可得D正确",
            "根据图中条件，f'(0)=? \\\\ f\\left(0\\right)=0,f'\\left(0\\right)=\\lim _{x\\to 0}\\frac{f\\left(x\\right)}{x} \\\\ \\lim _{x\\to 0}\\frac{f\\left(x\\right)}{1-\\cos x}=\\lim _{x\\to 0}\\frac{f\\left(x\\right)}{x^2}=1 \\\\ f'\\left(0\\right)=\\lim _{x\\to 0}\\frac{f\\left(x\\right)}{x^2}\\cdot x =1\\cdot 0=0 ",
        ],
        ["高阶导数的定义",
            "f^{\\left(n\\right)}\\left(x_0\\right)=\\lim _{\\triangle x\\to 0}\\frac{f^{\\left(n-1\\right)}\\left(x_0+\\triangle x\\right)-f^{\\left(n-1\\right)}\\left(x_0\\right)}{\\triangle x} \\\\ f^{\\left(n\\right)}\\left(x_0\\right)=\\lim _{x\\to x_0}\\frac{f^{\\left(n-1\\right)}\\left(x\\right)-f^{\\left(n-1\\right)}\\left(x_0\\right)}{x-x_0}",
            "\\frac{d^n\\left(uv\\right)}{dx^n}=?",
            "\\frac{d^n\\left(uv\\right)}{dx^n}=\\sum _{k=0}^nC_n^k\\cdot \\frac{d^k\\left(u\\right)}{dx^k}\\frac{d^{n-k}\\left(v\\right)}{dx^{n-k}}",
            "\\frac{d^n\\left(u\\pm v\\right)}{dx^n}=?",
            "\\frac{d^n\\left(u\\pm v\\right)}{dx^n}=\\frac{d^n\\left(u\\right)}{dx^n}\\pm \\frac{d^n\\left(v\\right)}{dx^n}",
            "\\frac{d^n\\left(\\cos x\\right)}{dx^n}=?",
            "\\frac{d^n\\left(\\cos x\\right)}{dx^n}=\\cos \\left(x+n\\cdot \\frac{\\pi }{2}\\right)",
            "\\frac{d^n\\left(\\sin x\\right)}{dx^n}=?",
            "\\frac{d^n\\left(\\sin x\\right)}{dx^n}=\\sin \\left(x+n\\cdot \\frac{\\pi }{2}\\right)",
            "求f\\left(x\\right)=x^22^x在x=0处的n阶导数",
            "解法1:莱布尼兹公式 \\\\\\frac{d^n\\left(uv\\right)}{dx^n}=\\sum _{k=0}^nC_n^k\\cdot \\frac{d^k\\left(u\\right)}{dx^k}\\frac{d^{n-k}\\left(v\\right)}{dx^{n-k}} \\\\ x^2在两阶导以后都是0,所以只需要前三项 \\\\ 题中要求的是x=0的层数,前两项都有x，消掉了 \\\\ f^{\\left(n\\right)}\\left(0\\right)=\\ C_n^2\\cdot \\left(x^2\\right)^{''}\\cdot \\left(2^x\\right)^{\\left(n-2\\right)} \\\\ \\ C_n^2=\\frac{n\\left(n+1\\right)}{2},\\left(x^2\\right)^{''}=2,\\left(2^x\\right)^{\\left(n-2\\right)}=2^x\\left[\\ln \\left(2\\right)\\right]^{n-2} \\\\ 注意左边的(n-2)是(n-2)阶导,右边是n-2次方",
            "解法2:2^x=e^{x\\ln 2} \\\\ 原式可以用e^x的泰勒展开 \\\\ x^2e^{x\\ln 2}=x^2\\left[1+\\left(x\\ln 2\\right)+...+\\frac{\\left(x\\ln 2\\right)^n}{n!}\\right] \\\\ 找到x^n的系数乘上n!就可得f^{(n)}(0) \\\\ 注意，括号外面还有一个x^2,它让所有x的次数都加2 \\\\ 所以真正要找的系数是: \\frac{\\left(\\ln 2\\right)^n}{\\left(n-2\\right)!},乘上n!就得到答案 ",
            "y=\\frac{1}{2x+3},求y^{(n)}(0)", "解法1,求前几阶导,找规律 \\\\ y'=\\left(-1\\right)\\left(2x+3\\right)^{-2}\\cdot2 \\\\ y''=\\left(-1\\right)\\left(-2\\right)\\left(2x+3\\right)^{-2}\\cdot 2^2 \\\\ y^{\\left(n\\right)}=\\left(-1\\right)^nn!\\left(2x+3\\right)^{-\\left(n+1\\right)}\\cdot 2^n,代入x=0即可",
            "解法2:要求y^{(n)}(0),可以用泰勒展开 \\\\ 有\\frac{1}{1+x}=1-x+x^2+...+\\left(-1\\right)^nx^n \\\\ 且\\frac{1}{2x+3}=\\frac{1}{3}\\left(\\frac{1}{1+\\frac{2}{3}x}\\right),将上式中x换为\\frac{2}{3}x \\\\ 得\\frac{1}{3}\\left(1-\\frac{2}{3}x+...+\\left(-1\\right)^n\\left(\\frac{2}{3}x\\right)^n\\right) \\\\ x^n的系数an=\\frac{f^{\\left(n\\right)}\\left(0\\right)}{n!}, 在上式中找到x^n的系数再×n!即可 \\\\ 得\\frac{1}{3}(-1)^n\\frac{2}{3}^n*n!",
        ],
        ["\\lim_{n\\to\\infty}[\\frac{n}{n^2+1}+\\frac{n}{n^2+2}+...+\\frac{n}{n^2+n}] \\\\ 这个极限等于0吗?",
            "这里看似\\frac{n}{n^2+1}=0 \\\\ 极限就是很多0加起来，所以等于零 \\\\ 但这个思路是错的，这里有无限项 \\\\ 不能这么加",
            "这道题的思路是用夹逼定理 \\\\ 把分母都换成n^2+n，分子加起来=n^2 \\\\ 所以 \\frac{n^2}{n^2+n} \\le [原式] \\le \\frac{n^2}{n^2+1} \\\\ n\\to\\infty时,两边都为1,所以极限为1",
        ],
        ["设f\\left(x\\right)=\\left|x\\left(1-x\\right)\\right| \\\\ 现在想知道0点附近的情况 \\\\ 请写出一、二阶导", "函数有绝对值，不好直接求导数 \\\\ 所以要先去绝对值,因为只关心0点小邻域的情况 \\\\ 可以把x看成很小的正数和很小的负数 \\\\ f(x)=-x(1-x), x<0 \\\\ f(x)=x(1-x), x\\ge0 \\\\ 0点左右两边的导数直接求即可 \\\\ 但是0点的导数是否存在还要单独讨论 \\\\ 本题不需要，所以不求"],
        ["\\lim _{x\\to +\\infty }\\frac{1}{x}+\\ln \\left(1+e^x\\right)-x=?",
            "\\frac{1}{x}是0,主要看后面两个 \\\\ \\infty-\\infty,按理说要通分，但该怎么做呢? \\\\ 我们发现x=\\ln \\left(e^x\\right),原式可以写成：\\\\ \\lim _{x\\to +\\infty }\\ln \\left(1+e^x\\right)-\\ln \\left(e^x\\right) \\\\ = \\lim _{x\\to +\\infty }\\ln \\left(\\frac{1+e^x}{e^x}\\right) =\\ln(1)=0 \\\\ 重点是：\\ln(..)-..可以把后面写成\\ln的形式",
            "除此之外也可以改\\ln,提一个e^x出来 \\\\ \\lim _{x\\to +\\infty }\\ln \\left(e^x\\left(\\frac{1}{e^x}+1\\right)\\right)-x \\\\ =\\lim _{x\\to +\\infty }x+\\ln \\left(1\\right)-x=0 "
        ],
        [
            "不等式证明专题",
            "证明\\frac{x}{1+x}<\\ln \\left(1+x\\right)<x,\\left(x>0\\right)",
            "\\ln(1+x)=\\ln(1+x)+\\ln(1) \\\\ 然后用拉格朗日中值定理 \\\\ \\ln \\left(1+x\\right)+\\ln \\left(1\\right)=\\frac{1+x-1}{c}=\\frac{x}{c} \\\\ c\\in(1,1+x), 不等式就要想到放缩 \\\\ \\frac{x}{1+x}<\\frac{x}{c}<\\frac{x}{1},分母小整体大 \\\\ 原式就证明完了, 以后看到\\ln就要想到可以加\\ln1 \\\\ 然后用中值定理改写，最后放缩即可 ",
            "证明当x>1时, \\frac{\\ln \\left(1+x\\right)}{\\ln x}>\\frac{x}{1+x}",
            "这题的关键是对式子变化 \\\\ 原式变为：\\left(1+x\\right)\\ln \\left(1+x\\right)>x\\ln x \\\\ 这个就是函数单调增的定义,令f(x)=x\\ln x \\\\ 只要证明f(x)单调增，本题就解决了 \\\\ 简单的十字相乘，把不等式证明转换成了求导判断正负 \\\\ f'\\left(x\\right)=\\ln x+1, 题中说了x>1 \\\\ 当x>1时,f'(x)恒大于0,f(x)单调增, 证毕 \\\\ 关键：不知道怎么做时，试着变化下式子",
        ],
        ["image:math_mvp1.png", "题目给了f(x)的信息，要证明f'(x)的东西 \\\\ 所以就想到中值定理能联系起来 \\\\ 要证明f'(\\xi)>0, f'\\left(\\xi \\right)=\\frac{f\\left(b\\right)-f\\left(a\\right)}{b-a} \\\\ 中值定理的几何意义就是有一点的斜率值 \\\\ 和区间上平均斜率相同,要平均斜率大于0,f(b)就要大于f(a) \\\\ 但题干中f(a)=f(b),这该怎么办呢? \\\\ 注意f(x)是不恒为常数的函数,所以在(a,b)间必有一点c \\\\ f(c) \\ne f(a), 假设f(c)>f(a),有\\frac{f\\left(c\\right)-f\\left(a\\right)}{c-a}>0 \\\\ 假设f(c)<f(a)=f(b),有\\frac{f\\left(b\\right)-f\\left(c\\right)}{b-c}>0 \\\\ 所以(a,b)之间至少存在一点\\xi,使得f(\\xi)>0"],
        ["image:math_mvp2.png",
            "f(x)在(0,+\\infty)上可导, 所以在(0,+\\infty)上连续 \\\\ 第一小问用介值定理证明就好 \\\\ 第二小问要证明 f'\\left(\\xi \\right)=\\frac{1}{a}, 我们发现 \\frac{f\\left(a\\right)-f\\left(0\\right)}{a-0}=\\frac{1}{a} \\\\ 所以第二小问用中值定理就证出来了 \\\\ 除此之外，也可以改写为 f'\\left(\\xi \\right)-\\frac{1}{a}=0 \\\\ 找到一个F(x)=\\int f'\\left(\\xi \\right)-\\frac{1}{a}dx, 就可以用罗尔定理算了 ",
            "(1).由于\\lim _{x\\to +\\infty }f\\left(x\\right)=2,则存在A>0,f(A)>1 \\\\ \\exists a\\in(0,A), 使 f(a)=1 \\\\ (2).\\frac{1}{a}=\\frac{f\\left(a\\right)-f\\left(0\\right)}{a-0}=f'(\\xi), \\xi\\in(0,a) \\\\ (2)解_2:f'\\left(\\xi \\right)-\\frac{1}{a}=0,F\\left(x\\right)=f\\left(x \\right)-\\frac{x}{a} \\\\ F(0)=F(a)=0, 则\\exists \\xi\\in(0,a),得F'(\\xi)=0 \\\\ 即f'\\left(\\xi \\right)=\\frac{1}{a}"
        ],
        ["\\lim_{n\\to\\infty}(\\frac{\\sqrt[n]{a}+\\sqrt[n]{b}+\\sqrt[n]{c}}{3})^n的思路?", `
            写成标准式: \\lim_{n\\to\\infty}(1 + \\frac{\\sqrt[n]{a}+\\sqrt[n]{b}+\\sqrt[n]{c}-3}{3})^n \\\\
            a(x) = \\frac{\\sqrt[n]{a}+\\sqrt[n]{b}+\\sqrt[n]{c}-3}{3}\\to 0, b(x)=n\\to\\infty \\\\ 
            \\lim_{n\\to\\infty}a(x)b(x)=\\frac{1}{3}\\frac{(a^{\\frac{1}{n}}-1)+(b^{\\frac{1}{n}}-1)+(c^{\\frac{1}{n}}-1)}{\\frac{1}{n}} \\\\ 
            有基本极限: \\lim_{x\\to 0}\\frac{a^x-1}{x}=\\ln(a),上式=\\ln(\\sqrt[3]{abc}) \\\\
            最终答案为: e^{\\ln(\\sqrt[3]{abc})} = \\sqrt[3]{abc}
        `],
        ["证明方程根存在和个数，一般用什么定理", "证明方程根存在,用零点定理、罗尔定理 \\\\ 证明方程根个数，用单调性",
            "image:math_f_r_p_1.png", "令f\\left(x\\right)=x+p+q\\cos x \\\\ \\lim _{x\\to +\\infty }f\\left(x\\right)=+\\infty , \\lim _{x\\to -\\infty }f\\left(x\\right)=-\\infty \\\\ 所以存在a<b, f(a)<0, f(b)>0 \\\\ 因此存在c\\in(a,b),使得f(c)=0 \\\\ f'(x)=1-q\\sin x, 且0<q<1 \\\\ f'(x)恒大于0,即函数f(x)单调递增 \\\\ 所以f(x)最多存在一个根",
            "恰有一个根，就是要证明存在一个根 \\\\ 还要证明只有一个根",
            "image:math_f_r_p_2.png", "这道题用零点定理做不了，考虑用罗尔定理 \\\\ 令g(x)=题干的方程, f(x)=\\int g(x)dx \\\\ f'(x)=g(x), 只要证明f(a)=f(b)就可用罗尔 \\\\ f(x)=a_nx^n+a_{n-1}x^{n-1}+...+a_2x^2+a_1x \\\\ f(0)=0, f(1)=a_n+a_{n+1}+...+a_2+a_1 \\\\ 由题目可知f(1)=0,f(1)=f(0) \\\\ 则\\exists c\\in(0,1), 使f'(x)=0, 证毕",
            "image:math_f_r_p_3.png",
            "题目要证明x^5-5x+k=0有三个实根 \\\\ 原式可以变成:k=5x-x^5,令f(x)=5x-x^5 \\\\ 它的几何意义是: f(x)与y=k相交了三次 \\\\ f'(x)=5-5x^4=5(1+x^2)(1-x^2) \\\\ x>1时，导数是负的,0<x<1时，导数是正的 \\\\ 即x>1时f(x)\\searrow，0<x<1时f(x)\\nearrow \\\\ 因为f'(x)是奇函数，f(x)<0的情况正好相反 \\\\ 即x>-1时f(x)\\searrow, 0<x<-1时f(x) \\nearrow \\\\ f(1)=4, f(-1)=-4, 可以把图画出来",
            "image:math_frp3_graph.png",
            "由图可见，y=k想和f(x)相交三次 \\\\ k\\in(-4,4) \\\\ k>4时只会相交一次 \\\\ k=4时相交两次"
        ],
        ["证明x\\ln \\frac{1+x}{1-x}+\\cos x\\ge 1+\\frac{x^2}{2} \\\\ (-1<x<1)", "首先把右边移过来 \\\\ f(x)=x\\ln \\frac{1+x}{1-x}+\\cos x-1-\\frac{x^2}{2}\\ge 0 \\\\ f(0)=0, 所以要不等式成立，只要证f(x)单调增 \\\\ 仔细观查一下,f(x)是个偶函数 \\\\ 所以只要证明f(x)在[0,1)上单调增即可  \\\\ f'\\left(x\\right)=\\ln \\frac{1+x}{1-x}+\\frac{2x}{1-x^2}-\\sin x-x \\\\ x\\in[0,1), \\frac{1+x}{1-x}\\ge1, \\ln \\frac{1+x}{1-x}\\ge0 \\\\ 1-x^2\\le1, 放缩一下，另x=0, 分母变大，整体变小 \\\\ f'(x)\\ge 2x-\\sin x-x=x-\\sin x",
            "当x\\in(0,\\frac{\\pi}{2})时,\\sin x < x < \\tan x \\\\ f'(x)\\ge x-\\sin x\\ge0,f(x)单调增 \\\\ 不等式证明完毕 \\\\ 要熟记常见的不等式,不等式一定要想起放缩 \\\\ 多关注函数奇偶性"
        ],
        ["设f(x)在(-\\infty,+\\infty)连续 \\\\ 其导函数图形如图所示 \\\\ (0,0)是一个极值点吗? \\\\ *注意！是导函数的图像，不函数的图像*", "image:math_extereme_value_problem_1.png", "在图中看到(0,0)的导数值不存在 \\\\ 但题干中有说在(-\\infty,+\\infty)连续 \\\\ 所以(0,0)存在极值 \\\\ 导数从正到负，所以是个极大值"],
        ["y=\\frac{1}{x}+\\ln \\left(1+e^x\\right)有斜渐近线吗?", "\\frac{1}{x}+\\ln \\left(1+e^x\\right) \\\\ =\\frac{1}{x}+\\ln \\left(e^x\\left(e^{-x}+1\\right)\\right) \\\\ =x+[\\frac{1}{x}+\\ln \\left(e^{-x}+1\\right)] \\\\ 其中方括号里\\to0, 符合ax+b+g(x) \\\\ 且x\\to\\infty,g(x)\\to0的形式 \\\\ (这里只有+\\infty趋向0,正半轴有斜渐近线) \\\\ 所以y=x是f(x)的斜渐近线"],
        ["\\lim _{n\\to \\infty }\\sqrt[n]{1+2^n+3^n}=?",
            "解法1:把最大项提出来 \\\\ \\lim _{n\\to \\infty }3\\sqrt[n]{\\left(\\frac{1}{3}\\right)^n+\\left(\\frac{2}{3}\\right)^n+1}=3 \\\\ 解法2: 夹逼定理 \\\\ \\sqrt[n]{3^n}\\le \\sqrt[n]{1+2^n+3^n}\\le \\sqrt[n]{3\\cdot 3^n} \\\\ 两边都为3，所以极限为3 ",
            "\\lim _{x\\to \\infty }\\sqrt[n]{a_1^n+a_2^n+\\dots +a_m^n} \\\\ a_i > 0, (i=0,1,2,3,\\dots,m)","极限为A, A=\\max(a_i)",
            "求极限\\lim _{x\\to \\infty }\\sqrt[n]{2+x^n+\\left(\\frac{x^2}{2}\\right)^n}",
            "如果这里的2换成1,就能写成1^n \\\\ 这样极限的值就是\\max(1,x,\\frac{x^2}{2}) \\\\ 但其实，2=1+1,也就是1^n+1^n \\\\ 这里2换成任何常数都可以这么做",
        ],
        ["证明f(x)=x\\sin(x)是无界函数","由于f(2n\\pi+\\frac{\\pi}{2})=2n\\pi+\\frac{\\pi}{2} \\\\ 所以对任意的M>0，只要正整数n充分大 \\\\ 总有 |f(2n\\pi+\\frac{\\pi}{2})|=2n\\pi+\\frac{\\pi}{2}>M \\\\ 故f(x)=x\\sin(x)是无界函数"],
        ["\\int \\frac{1}{(x^2+4)^2}dx 思路","x=2\\tan\\theta \\\\ 不是只在根号下才能用三角函数替换 \\\\ 打开思路"],
        ["\\sum_{n=m}^{\\infty}ar^n的收敛发散情况?","若r \\in (-1, 1), 级数收敛于\\frac{首项}{1-r} \\\\ 若 r \\in [1,+\\infty) 或 r \\in (-\\infty,-1], 级数发散"],
        ["\\int \\ln(x)dx \\\\ 解题思路?", "\\ln(x)的积分不是\\frac{1}{x} \\\\ 这个积分要分部积分来算"],
        ["\\int \\frac{1}{\\sqrt{x-x^2}}dx \\\\ 解题思路?", "把x提出来，剩下\\sqrt{1-x} \\\\ 可以看作\\sqrt{1-\\sqrt{x}^2} \\\\ 重点是x可以看做\\sqrt{x}^2 \\\\ 变成熟悉的常见导数"],
        ["\\int e^{2x}\\cos(x)dx \\\\ 解题思路?", "类似\\sin,\\cos,e^x等  \\\\ 求导两次会变回自身的 \\\\ 多次分部积分 \\\\ 移动到等式左边解出原式"],
        ["\\int \\cos(\\sqrt{x})dx 思路", "u=\\sqrt{x} \\\\ u^2 = x \\\\ 2udu=dx \\\\ 换元两边求导，x也要有dx "],
        ["\\int \\frac{1}{x^2\\sqrt{x^2+1}} 思路", "变成\\int \\frac{x^{-3}}{\\sqrt{1+x^{-2}}} \\\\ 分数尽量写成负次幂 \\\\ 多考虑负次幂换元的可能"],
        ["\\int \\csc^3(x)\\sec(x)", "1可以看做\\sin^2 + \\cos^2"],
        ["\\int \\frac{x^2+1}{x^4-x^2+1}", "因式分解不了的,就配方 \\\\ 每次变动后检查能否换元 \\\\ 尝试配成常见的导数"],
        ["\\int \\frac{\\cos(2x)}{\\sin(x)+\\cos(x)}", "\\cos(2x)变成平方差\\cos^2(x)-\\sin^2(x)"],
        ["求\\int \\sec(x)的思路", "\\sec(x) * \\frac{\\sec(x)+\\tan(x)}{\\sec(x)+\\tan(x)} \\\\ 构造\\frac{f'(x)}{f(x)}"],
    ],
}