export default {
    name: "new",
    cards: [
        ["x=\\sqrt{t^2+1} \\\\ y=\\ln \\left(t+\\sqrt{t^2+1}\\right) \\\\ 求 \\left.\\frac{d^2y}{dx^2}\\right\\vert_{t=1} ", "\\frac{dy}{dx}=\\frac{\\frac{1}{\\sqrt{1+t^2}}}{\\frac{2t}{2\\sqrt{t^2+1}}}=\\frac{1}{t} \\\\ 这一步一定要注意化简 \\\\ 否则又复杂又容易错 \\\\ 最终答案是-\\sqrt{2}"],
        ["参数方程求导", "image:parametric_function_derivative.png"],
        ["若f(x)可导，那其反函数的导数是什么?", "若y=f(x)可导,且f'(x)\\ne0 \\\\ 其反函数x=\\phi(y)也可导 \\\\ \\phi'(y)=\\frac{1}{f'(x)} \\\\ f'(x)是切线关于x轴夹角\\alpha的\\tan \\alpha值 \\\\ \\phi'(y)是关于y轴夹角\\beta的\\tan \\beta值 \\\\ \\beta = \\frac{\\pi}{2}-\\alpha, 所以两者\\tan互为倒数"],
        ["f(x)+f(-x)是个什么函数? \\\\ f(x)-f(-x)是什么函数?", "偶函数，不论f(x)是什么函数 \\\\ f(x)+f(-x)都是偶函数 \\\\ f(x)-f(-x)都是奇函数"],
        ["若f(x)可导，f'(x)的奇偶性如何?", "若f(x)可导 \\\\ 且f(x)为奇函数, 那么f'(x)为偶函数 \\\\ 若f(x)为偶函数,那么f'(x)为奇函数 \\\\ 若f(x)为周期函数,那么f'(x)也为周期函数"],
        ["image:derivative_1.png", "在x_0处的导数，一定与f(x_0)的定义相关 \\\\ 题目中以及A和B选项中,都没说明f(0)的定义 \\\\ 但是又说x=0处可导，所以A,B一定错 \\\\ C,D都说x=0处可导,所以x=0处一定连续 \\\\ 因为连续,可从题干中\\lim_{x\\to0}f(x)=0得到f(0)=0 \\\\ f'\\left(0\\right)=\\lim _{x\\to 0}\\frac{f\\left(x\\right)}{x} 存在,分母趋向0,那分子也趋向0 \\\\ 能模糊感觉到f(x)是和x同阶或高阶无穷小 \\\\ 所以感觉C是正确的,要证明的话就上下同除x \\\\ \\lim _{x\\to 0}\\frac{f\\left(x\\right)/x}{\\sqrt{\\left|x\\right|}/x}=\\lim _{x\\to 0}\\frac{f\\left(x\\right)}{x}\\frac{x}{\\sqrt{\\left|x\\right|}}=0"],
        ["f(x)在x_0的某领域可导,能推出: \\\\ f'(x)在x_0点处连续 \\\\ \\lim_{x\\to x_0} f'(x)存在吗?", "f(x)在x_0的某领域可导 \\\\ 推不出f'(x)在x_0点处连续 \\\\ 也推不出 \\lim_{x\\to x_0} f'(x)存在"],
        ["连续、可导、可微之间的关系", "image:relation_c_d.png"],
        ["两条垂直线斜率的关系", "两条垂直线斜率互为负倒数"],
        ["求曲线f(x)在点(x_0,f(x_0))的切线方程", "切线方程:y-f(x_0)=f'(x_0)(x-x_0) \\\\ 法线方程:y-f(x_0)=-\\frac{1}{f'(x_0)}(x-x_0)"],
        ["可导的定义", "text:点A可导$\\iff$点A左右导数存在且相等 \n 在区间[a,b]上可导:在(a,b)每一点都可导 \n 且左端点处有右导数，右端点处有左导数 \n 则称函数f(x)在[a,b]上可导"],
        ["左右导数的定义", "左导数:f_-'\\left(x_0\\right)=\\lim _{\\triangle x\\to 0^-}\\frac{f\\left(x_0+\\triangle x\\right)-f\\left(x_0\\right)}{\\triangle x} \\\\ 右导数: f_+'\\left(x_0\\right)=\\lim _{\\triangle x\\to 0^+}\\frac{f\\left(x_0+\\triangle x\\right)-f\\left(x_0\\right)}{\\triangle x}"],
        ["导数的定义", "f'\\left(x_0\\right)=\\lim _{\\triangle x\\to 0}\\frac{f\\left(x_0+\\triangle x\\right)-f\\left(x_0\\right)}{\\triangle x} \\\\ f'\\left(x_0\\right)=\\lim _{\\triangle x\\to x_0}\\frac{f\\left(x\\right)-f\\left(x_0\\right)}{x-x0}"],

        ["f(x)在[a,b]上连续,a<c<d<b \\\\ 证明:对任意正数p,q,至少存在一个\\xi \\\\ 使pf\\left(c\\right)+qf\\left(d\\right)=\\left(p+q\\right)f\\left(\\xi \\right)", "题目其实是要证明:\\frac{pf\\left(c\\right)+qf\\left(d\\right)}{\\left(p+q\\right)}=f\\left(\\xi \\right) \\\\ 根据介值定理推论可知，只要等号左边介于最大值和最小值 \\\\ 等式就成立。如果f(c)和f(d)相等，p+q就能消掉 \\\\ 令f(c)和f(d)都等于[c,d]上的最大值M和最小值m \\\\ \\frac{\\left(p+q\\right)m}{\\left(p+q\\right)}\\le \\frac{pf\\left(c\\right)+qf\\left(d\\right)}{\\left(p+q\\right)}\\le \\frac{\\left(p+qf\\right)M}{\\left(p+q\\right)} \\\\ 关键要能看出题目与介值定理的关系,和如何放缩"],
        ["\\lim _{n\\to \\infty }a^{\\frac{1}{n}}=\\lim _{n\\to \\infty }\\sqrt[n]{a}=?", "\\lim _{n\\to \\infty }a^{\\frac{1}{n}}=\\lim _{n\\to \\infty }\\sqrt[n]{a}=1(a>0)"],
        ["\\lim _{n\\to \\infty }n^{\\frac{1}{n}}=\\lim _{n\\to \\infty }\\sqrt[n]{n}=?", "\\lim _{n\\to \\infty }n^{\\frac{1}{n}}=\\lim _{n\\to \\infty }\\sqrt[n]{n}=1"],
        ["f\\left(x\\right)=\\lim _{n\\to \\infty }\\frac{1+x}{1+x^{2n}} \\\\ 找到f(x)的间断点","注意！这里f(x)是一个极限的形式 \\\\ 需要先求极限，把表达式写出来 \\\\ f\\left(x\\right)=1,x=1 \\\\ f\\left(x\\right)=1+x,\\left|x\\right|<1 \\\\ f\\left(x\\right)=0,\\left|x\\right|>1 \\\\ f\\left(x\\right)=0,x=-1"],
        ["\\lim _{x\\to 0}x\\ln \\left|x\\right|\\sin \\frac{1}{x}=?","x\\to0,\\sin \\frac{1}{x}在-1,1之间振荡 \\\\ x\\ln \\left|x\\right|=\\frac{\\ln \\left|x\\right|}{\\frac{1}{x}}=\\frac{\\frac{1}{x}}{\\frac{1}{x^2}}=0 \\\\ 无穷量×有界量=0,所以极限值为0"],
        ["讨论 f\\left(x\\right)=\\frac{x}{1-e^{\\frac{x}{1-x}}} 的连续性 \\\\ 并指出间断点类型","f(x)在x=1和x=0上没意义，是间断点 \\\\ 解:由于f(x)是初等函数，则除x=0,1时处处连续 \\\\ \\lim _{x\\to 0}\\frac{x}{-\\frac{x}{1-x}}=-1, x=0是可去间断点 \\\\ \\lim _{x\\to 1^-}\\frac{1}{1-\\infty }=0, \\lim _{x\\to 1^+}\\frac{1}{1-0}=1 \\\\ 左右极限存在但不同，所以是跳跃间断点 \\\\ e^{\\infty}要特别注意左右极限不同"],
        ["介值定理","若f(x)在[a,b]上连续，且f(a)\\ne f(b) \\\\ 则对f(a)与f(b)之间任意值N \\\\ 在[a,b]之间至少有一点c, 使得f(c)=N"],
        ["最值定理","若f(x)在[a,b]上连续 \\\\ 则f(x)在[a,b]上必有最大值和最小值"],
        ["若f(x)在[a,b]上连续，那么有界性是?","若f(x)在[a,b]上连续 \\\\ 则f(x)在[a,b]上有界"],
        ["初等函数是连续的吗?","初等函数由初等基本函数 \\\\ 经过有限次的复合得到 \\\\ 初等函数在其定义区间内连续 \\\\ 注意这里说的是定义区间，而不是定义域 \\\\ 例: \\sqrt{\\cos(x)-1} 的定义域为离散的点 \\\\ 离散的点无从谈起连续，都是离散的点也没有定义区间"],
        ["连续函数的复合是连续的吗？","连续函数的复合仍为连续函数"],
        ["连续函数的和、差、积、商仍为连续函数吗？","连续函数的和、差、积、商仍为连续函数! \\\\ 商分母不为0"],
        ["f\\left(x\\right)=\\frac{\\ln \\left|x\\right|}{\\left|x-1\\right|}\\sin x \\\\ f(x)有几个间断点，它们分别是什么类型","x=0时,\\ln|x|没有意义 \\\\ \\lim _{x\\to \\ 0}\\frac{\\ln \\left|x\\right|}{\\left|x-1\\right|}\\sin x =\\lim _{x\\to \\ 0}\\ln \\left|x\\right|\\sin x \\\\ 0×\\infty,把\\sin x 等价代换后放到分母上 \\\\ =\\lim _{x\\to \\ 0}\\frac{\\ln \\left|x\\right|}{\\frac{1}{x}}=\\lim _{x\\to \\ 0}\\frac{\\frac{1}{x}}{-\\frac{1}{x^2}}=0 \\\\ 极限存在，所以x=0是一个可去间断点 \\\\ x=1时分母为0, 代入后\\sin(1)为非零因子，提出来 \\\\ =\\sin 1\\lim _{x\\to 1}\\frac{\\ln \\left(x\\right)}{\\left|x-1\\right|}=\\sin 1\\lim _{x\\to 1}\\frac{\\ln \\left(1+x-1\\right)}{\\left|x-1\\right|} \\\\ 等价代换 \\sin 1\\lim _{x\\to 1}\\frac{x-1}{\\left|x-1\\right|}, 左右极限分别为-1,1 \\\\ 左右极限不同，所以x=1是一个跳跃间断点"],
        ["\\frac{d}{dx} \\ln|x|","\\frac{1}{x}"],
        ["第二类间断点","左右极限中至少有一个不存在 \\\\ 无穷间断点：x\\to0, f(x)=\\frac{1}{x} \\\\ 振荡间断点：x\\to0, f(x)=\\sin(\\frac{1}{x})"],
        ["第一类间断点","左右极限都存在的间断点 \\\\ 可去间断点：左极限=右极限 \\\\ 跳跃间断点：左极限\\ne右极限"],
        ["间断点的定义","若f(x)在x_0某去心领域有定义 \\\\ 但在x_0处不连续 \\\\ 则称x_0为f(x)的间断点"],
        ["f(x) 在[a,b]上连续的定义","若f(x)在(a,b)上的每一点都连续 \\\\ 且f(x)在a点处右连续，在b点处左连续 \\\\ 则称函数f(x)在[a,b]上连续"],
        ["\\lim _{x\\to x_0^+}f\\left(x\\right)=f\\left(x_0\\right) \\\\ 则称?","若\\lim _{x\\to x_0^+}f\\left(x\\right)=f\\left(x_0\\right) \\\\ 则称f(x)在x_0点处右连续 \\\\ f\\left(x\\right)连续\\Leftrightarrow f\\left(x\\right)左连续且右连续"],
        ["\\lim _{x\\to x_0^-}f\\left(x\\right)=f\\left(x_0\\right) \\\\ 则称?","若\\lim _{x\\to x_0^-}f\\left(x\\right)=f\\left(x_0\\right) \\\\ 则称f(x)在x_0点处左连续 \\\\ f\\left(x\\right)连续\\Leftrightarrow f\\left(x\\right)左连续且右连续"],
        ["连续的定义1 \\\\ \\lim_{\\triangle x\\to0}\\triangle y=?","\\lim _{\\triangle x\\to 0}\\triangle y=\\lim _{\\triangle x\\to 0}\\left[f\\left(x_0+\\triangle x\\right)-f\\left(x_0\\right)\\right]=0 \\\\ 当x的改变量趋于0时，函数值的改变量也趋于0"],
        ["n\\to\\infty时，\\left(1+\\frac{1}{n}\\right)^n-e \\sim \\frac{b}{n^a} \\\\ 求a,b","\\left(1+\\frac{1}{n}\\right)^n-e=e^{n\\ln \\left(1+\\frac{1}{n}\\right)}-e \\\\ =e\\left(e^{n\\ln \\left(1+\\frac{1}{n}\\right)-1}-1\\right) \\\\ \\sim e\\left(n\\ln \\left(1+\\frac{1}{n}\\right)-1\\right) \\\\ =en\\left(\\ln \\left(1+\\frac{1}{n}\\right)-\\frac{1}{n}\\right) \\\\ \\sim en\\left(-\\frac{1}{2}\\left(\\frac{1}{n}\\right)^2\\right) =-\\frac{e}{2n} \\\\ \\therefore a=1, b= -\\frac{e}{2n} "],
        ["1-\\cos^\\alpha(x) \\sim ? \\\\ 写出证明","1-\\cos^\\alpha(x) \\sim \\frac{\\alpha}{2}x^2 \\\\ 证: 1-\\cos ^{\\alpha }x=1-\\left(1+\\cos x-1\\right)^{\\alpha } \\\\ =-\\left(\\left(1+\\cos x-1\\right)^{\\alpha }-1\\right) \\\\ \\sim -\\alpha \\left(\\cos x-1\\right) \\\\ \\sim -\\alpha \\cdot -\\frac{1}{2}x^2 = \\frac{\\alpha }{2}x^2"],
        ["如何用定积分的定义求极限","1.提出\\frac{1}{n},把变化的地方写成x \\\\ 2.看变化的地方的极限，写出上下限 \\\\ 3.确认\\frac{1}{n}是否准确，是否要补项"],
        ["image:infinite_small_2_ques.png", "image:infinite_small_2_ans.png"],
        ["image:infinite_small_1_ques.png", "image:infinite_small_1_ans.png"],
        ["定积分的定义","\\lim _{n\\to \\infty }\\frac{1}{n}\\sum _{i=1}^nf\\left(\\frac{i}{n}\\right)=\\int _0^1f\\left(x\\right)dx \\\\ 基中n是将图形切分的份数,n越大,越精确"],
        ["涉及a,b的不等式关系 \\\\ 涉及a,b,c的不等式关系","2ab\\le a^2+b^2 \\\\ \\sqrt[3]{abc}\\le \\frac{a+b+3}{3}"],
        ["求极限\\lim _{x\\to \\infty }\\sqrt[n]{2+x^n+\\left(\\frac{x^2}{2}\\right)^n}","如果这里的2换成1,就能写成1^n \\\\ 这样极限的值就是\\max(1,x,\\frac{x^2}{2}) \\\\ 但其实，2=1+1,也就是1^n+1^n \\\\ 这里2换成任何常数都可以这么做"],
        ["\\lim _{x\\to \\infty }\\sqrt[n]{a_1^n+a_2^n+\\dots +a_m^n} \\\\ a_i > 0, (i=0,1,2,3,\\dots,m)","极限为A, A=\\max(a_i)"],
        ["\\lim _{n\\to \\infty }\\sqrt[n]{1+2^n+3^n}=?","解法1:把最大项提出来 \\\\ \\lim _{n\\to \\infty }3\\sqrt[n]{\\left(\\frac{1}{3}\\right)^n+\\left(\\frac{2}{3}\\right)^n+1}=3 \\\\ 解法2: 夹逼定理 \\\\ \\sqrt[n]{3^n}\\le \\sqrt[n]{1+2^n+3^n}\\le \\sqrt[n]{3\\cdot 3^n} \\\\ 两边都为3，所以极限为3 "],
        ["\\lim _{x\\to 0}\\left(\\frac{\\sin 6x+xf\\left(x\\right)}{x^3}\\right)=0 \\\\ 那么\\lim _{x\\to 0}\\left(\\frac{6+f\\left(x\\right)}{x^2}\\right)=? \\\\ 用等价代换","\\lim _{x\\to 0}\\left(\\frac{\\sin 6x-6x+xf\\left(x\\right)+6x}{x^3}\\right)=0 \\\\ \\lim _{x\\to 0}\\frac{\\sin 6x-6x}{x^3}+\\lim _{x\\to 0}\\frac{xf\\left(x\\right)+6x}{x^3}=0 \\\\ \\lim _{x\\to 0}\\frac{-\\frac{1}{6}\\left(6x\\right)^3}{x^3}+\\lim _{x\\to 0}\\frac{f\\left(x\\right)+6}{x^2}=0 \\\\ ans=36 "],
        ["\\lim _{x\\to 0}\\left(\\frac{\\sin 6x+xf\\left(x\\right)}{x^3}\\right)=0 \\\\ 那么\\lim _{x\\to 0}\\left(\\frac{6+f\\left(x\\right)}{x^2}\\right)=? ","\\\\ \\lim _{x\\to 0}\\left(\\frac{6x-\\frac{\\left(6x\\right)^3}{6}+xf\\left(x\\right)}{x^3}\\right)=0 \\\\ \\lim _{x\\to 0}\\frac{6x+xf\\left(x\\right)}{x^3}-\\lim _{x\\to 0}\\frac{\\left(6x\\right)^3}{x^3}=0 \\\\ \\lim _{x\\to 0}\\frac{6+f\\left(x\\right)}{x^2}-36=0"],
        ["\\lim _{x\\to 0}\\frac{\\ln \\left(1+x\\right)-\\left(ax+bx^2\\right)}{x^2}=2 \\\\ 求a,b的思路","用泰勒替换\\ln(1+x),展开到2次即可(分母) \\\\ \\ln(1+x)=x-\\frac{x^2}{2}+o(x^2) \\\\ 整理后: \\lim _{x\\to 0}\\frac{\\left(1-a\\right)x-\\left(\\frac{1}{2}+b\\right)x^2+o\\left(x^2\\right)}{x^2}=2 \\\\ 极限值是存在的=2,\\frac{\\left(1-a\\right)x}{x^2}的极限是无穷 \\\\ 所以(1-a)要为0,把式子中的无穷去掉, a=1 \\\\ \\frac{o\\left(x^2\\right)}{x^2}=0, 所以-\\frac{\\left(\\frac{1}{2}+b\\right)x^2}{x^2}=2, b=-\\frac{5}{2}"],
        ["\\lim _{x\\to 0}\\frac{\\cos x-e^{-\\frac{x^2}{2}}}{x^4} 思路","洛必达和等价代换不太好做,用泰勒 \\\\ 分母是4次,所以展开到4次就行 \\\\ \\cos x=1-\\frac{x^2}{2}+\\frac{x^4}{24}+o\\left(x^4\\right) \\\\ e^{-\\frac{x^2}{2}}=1+\\left(-\\frac{x^2}{2}\\right)+\\left(-\\frac{x^2}{2}\\right)^2+o\\left(x^4\\right) \\\\ 代入原式后分子剩下 -\\frac{1}{12}+o(x^4) \\\\ 两个o(x^4)形式一样，真实值不同, 所以没被消掉 \\\\ 最后极限值为: -\\frac{1}{12}"],
        ["若a\\sim b, a=?","a=b+o(b)"],
        ["若f(x)n阶可导 \\\\ 洛必达能洛到几阶导出现 \\\\ 若f(x)有n阶连续导数呢","若f(x)n阶可导 \\\\ 洛必达只能出现f^{(n-1)}(x) \\\\ 若f(x)有n阶连续导数 \\\\ 洛必达能出现f^{(n)}(x)"],
        ["\\lim _{x\\to 1}\\left(1-x^2\\right)\\tan \\left(\\frac{\\pi }{2}x\\right) 的巧算", "原式=\\lim _{x\\to 1}\\left(1-x\\right)\\left(1+x\\right)\\frac{\\sin \\left(\\frac{\\pi }{2}x\\right)}{\\cos \\left(\\frac{\\pi }{2}x\\right)} \\\\ 其中(1+x)和\\sin \\frac{\\pi}{2}x是非零的因子，可以先算 \\\\ 原式=2\\lim _{x\\to 1}\\frac{\\left(1-x\\right)}{\\cos \\left(\\frac{\\pi }{2}x\\right)}, 洛必达就很方便了 \\\\ 极限值为\\frac{4}{\\pi}"],
        ["\\lim _{x\\to 0}\\frac{\\sin x}{e^x-a}\\left(\\cos x-b\\right)=5, \\\\ 求a,b", "\\lim _{x\\to 0}\\frac{\\sin x\\left(\\cos x-b\\right)}{e^x-a}=5,分子趋向0 \\\\ 极限存在且不为0,那分母就一定趋向0 \\\\ \\lim_{x\\to0}e^x-a=0, 得a=1, 代入原式 \\\\ \\lim _{x\\to 0}\\frac{\\sin x\\left(\\cos x-b\\right)}{e^x-1}=5 等价代换 \\\\ \\lim _{x\\to 0}\\left(\\cos x-b\\right)=5,得b=-4 "],
        ["\\lim _{x\\to \\infty }\\left[\\left(ax+b\\right)e^{\\frac{1}{x}}-x\\right]=2 \\\\ 求a,b", "知道极限求参数,先找到存在的项提出来 \\\\ \\lim _{x\\to \\infty }\\left(axe^{\\frac{1}{x}}-x\\right)+b\\lim _{x\\to \\infty }e^{\\frac{1}{x}}=2 \\\\ \\lim _{x\\to \\infty }x\\left(ae^{\\frac{1}{x}}-1\\right)+b=2 \\\\ 因为极限存在,x\\to\\infty,所以括号里的东西\\to0 \\\\ a-1 = 0, 得a=1 \\\\ 上式变成 \\lim _{x\\to \\infty }x\\left(e^{\\frac{1}{x}}-1\\right)+b=2 \\\\ 等价代换后 \\lim _{x\\to \\infty }x\\cdot \\frac{1}{x}+b=2 \\\\ \\therefore a=b=1 "],
        ["\\lim _{x\\to 0}\\left[\\frac{1}{x}-\\left(\\frac{1}{x}-a\\right)e^x\\right]=1 \\\\ 求a思路?", "对于知道极限求参数的题，先找到存在的项提出来 \\\\ 原式= \\lim _{x\\to 0}\\left(\\frac{1-e^x}{x}\\right)+a\\lim _{x\\to 0}e^x=1 \\\\ a\\lim _{x\\to 0}e^x这项是存在的,原式的极限也是存在的 \\\\ 所以剩下的项的极限也是存在的 \\\\ 等价代换后得a=2"],
        ["若\\lim f(x)g(x)存在,且\\lim f(x)\\to\\infty \\\\ 证明\\lim g(x)\\to0", "\\lim f\\left(x\\right)g\\left(x\\right)=A \\\\ \\lim g\\left(x\\right)=\\lim \\left(\\frac{f\\left(x\\right)g\\left(x\\right)}{f\\left(x\\right)}\\right) \\\\ \\lim f(x)g(x) 趋向有限值, f(x)趋向无穷 \\\\ \\therefore \\lim g(x)\\to0"],
        ["\\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\right)=A\\ne 0,\\lim f\\left(x\\right)\\to 0 \\\\ 分子趋向0", "\\lim g\\left(x\\right)=\\lim \\left(\\frac{g\\left(x\\right)}{f\\left(x\\right)}\\cdot f\\left(x\\right)\\right) \\\\ =\\lim \\left(\\frac{g\\left(x\\right)}{f\\left(x\\right)}\\right)\\lim \\left(f\\left(x\\right)\\right) \\\\ =\\frac{1}{\\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\right)}\\lim \\left(f\\left(x\\right)\\right) \\\\ 已知 \\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\right)=A\\ne 0 \\\\ \\therefore \\lim g(x)=\\frac{1}{A}\\cdot 0=0"],
        ["\\lim \\frac{f\\left(x\\right)}{g\\left(x\\right)}存在, 且\\lim g(x)\\to0 \\\\ 分母趋向0", "那么\\lim f(x)也\\to0 \\\\ \\lim f(x) = \\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\cdot g\\left(x\\right)\\right) =0 "],
        ["\\lim f\\left(x\\right)存在,\\lim g\\left(x\\right)不存在 \\\\ \\lim \\left(f\\left(x\\right)\\pm g\\left(x\\right)\\right) 存在吗? ", "不存在 \\\\ \\lim F\\left(x\\right)=\\lim \\left(f\\left(x\\right)+g\\left(x\\right)\\right) \\\\ \\lim g\\left(x\\right)=\\lim F\\left(x\\right)-\\lim f\\left(x\\right) \\\\ 若F(x)的极限存在, f(x)的极限也存在 \\\\ 那两个极限相减也存在,这就矛盾了 \\\\ \\therefore 存在+不存在=不存在"],
        ["\\lim f\\left(x\\right)=A,\\lim g\\left(x\\right)=B \\\\ 极限的有理运算法则为?", "\\lim \\left(f\\left(x\\right)\\pm g\\left(x\\right)\\right)=\\lim f\\left(x\\right)\\pm \\lim g\\left(x\\right) \\\\ \\lim \\left(f\\left(x\\right)\\cdot g\\left(x\\right)\\right)=\\lim f\\left(x\\right)\\cdot \\lim g\\left(x\\right) \\\\  \\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\right)=\\frac{\\lim f\\left(x\\right)}{\\lim g\\left(x\\right)}\\left(B\\ne 0\\right) \\\\ 使用的前提是f(x)和g(x)的极限都存在"],
        ["\\lim _{x\\to 0}\\frac{x-\\ln \\left(1+\\tan x\\right)}{x^2}思路", "已知x-\\ln \\left(1+x\\right)\\sim \\frac{1}{2}x^2 \\\\ 但此时外面是x里面是\\tan x,不能直接换 \\\\ 我们可以两边同时减去\\tan x \\\\ \\lim _{x\\to 0}\\frac{\\left(x-\\tan x\\right)-\\left[\\ln \\left(1+\\tan x\\right)-\\tan x\\right]}{x^2} \\\\ x-\\tan x\\sim -\\frac{1}{3}x^3, \\ln\\left(1+\\tan x\\right)-\\tan x\\sim-\\frac{1}{2}\\tan^{2}x \\\\ 减法两边比值不为1,可以等价代换"],
        ["\\lim_{x\\to0}\\frac{\\arcsin x-\\sin x}{\\arctan x-\\tan x}思路", "减法想等价代换需要两边比值不为1 \\\\ \\arcsin x \\sim x, \\sin x \\sim x, 比值为1,没法直接换 \\\\ 但可以加上x变成 \\lim_{x\\to0}\\frac{(\\arcsin x -x)-(\\sin x-x)}{(\\arctan x-x)-(\\tan x-x)} \\\\ \\arcsin x-x \\sim \\frac{1}{6}x^3, \\sin x-x \\sim -\\frac{1}{6}x^3 \\\\ \\arctan x-x \\sim -\\frac{1}{3}x^3, \\tan x-x \\sim \\frac{1}{3}x^3 \\\\ 两边比值不为1,可以等价代换"],
        ["当x\\to0,(1+x)^a-1 \\sim ax \\\\ 这可结论可推广为:", "若a(x)\\to0,a(x)b(x)\\to0 \\\\ 则(1+a(x))^{b(x)} \\sim a(x)b(x) \\\\ 条件要求a(x)\\to0, a(x)b(x)\\to0 \\\\ 所以b(x)可以不\\to0"],
        ["幂指函数求极限的作法 \\\\ \\lim_{x\\to0}(\\frac{2+\\cos x}{3})^x-1", "将幂指函数改写为e^{\\ln(...)}, 再用e^x-1 \\sim x 代换 \\\\ \\lim_{x\\to0}e^{x\\ln(\\frac{2+\\cos x}{3})}-1, e的指数趋于0,可以代换 \\\\ \\lim_{x\\to0}x\\ln(\\frac{2+\\cos x}{3})"],
        ["\\lim_{x\\to 0}\\frac{\\ln(\\cos x)}{x^2}=?", "\\frac{0}{0}型第一反应用洛必达 \\\\ 得\\lim_{x\\to 0}\\frac{-\\tan x}{2x}, 还是\\frac{0}{0}, 再洛? \\\\ 这一步就可以用无穷小代换, \\tan x \\sim x \\\\ 极限值为-\\frac{1}{2}, 所以不要一条路洛到底 \\\\ 要灵活应用, 这题也可以写成 \\ln(1+\\cos x - 1) \\\\ 等价代换为 -(1-\\cos x),再换-\\frac{1}{2}x^2"],
        ["\\lim_{x\\to 0}\\frac{\\sqrt{1+f(x)\\sin(2x)}-1}{e^{3x}-1}=2 \\\\ 那么\\lim_{x\\to 0}f(x)=?", "这道题的思路是等价无穷小代换 \\\\ 分母可以用 e^x-1 \\sim x \\\\ 看似分子也可以用 (1+x)^a-1 \\sim ax \\\\ 但使用前需要确定f(x)\\sin(2x) \\to 0 \\\\ 若极限的商存在，且分母\\to0,那分子也\\to 0 \\\\ 所以 \\lim_{x\\to0}\\frac{\\frac{1}{2}f(x)2x}{3x}=2, f(x)=6"],
        ["a^x-1的等价无穷小", "a^x-1 \\sim x\\ln(a)"],
        ["等价无穷小代换原则", "乘除可以换, 若a\\sim a_1, b\\sim b_1 \\\\ 且 \\lim \\frac{a_1}{b_1}=A\\ne1 则减法可以换 \\\\ a-b \\sim a_1-b_1 \\\\ 若 \\lim \\frac{a_1}{b_1}=A\\ne-1 则加法可以换 \\\\ a+b \\sim a_1+b_1  "],
        ["\\lim_{n\\to\\infty}(\\frac{\\sqrt[n]{a}+\\sqrt[n]{b}+\\sqrt[n]{c}}{3})^n的思路?", `
            写成标准式: \\lim_{n\\to\\infty}(1 + \\frac{\\sqrt[n]{a}+\\sqrt[n]{b}+\\sqrt[n]{c}-3}{3})^n \\\\
            a(x) = \\frac{\\sqrt[n]{a}+\\sqrt[n]{b}+\\sqrt[n]{c}-3}{3}\\to 0, b(x)=n\\to\\infty \\\\ 
            \\lim_{n\\to\\infty}a(x)b(x)=\\frac{1}{3}\\frac{(a^{\\frac{1}{n}}-1)+(b^{\\frac{1}{n}}-1)+(c^{\\frac{1}{n}}-1)}{\\frac{1}{n}} \\\\ 
            有基本极限: \\lim_{x\\to 0}\\frac{a^x-1}{x}=\\ln(a),上式=\\ln(\\sqrt[3]{abc}) \\\\
            最终答案为: e^{\\ln(\\sqrt[3]{abc})} = \\sqrt[3]{abc}
        `],
        ["\\lim_{x\\to\\infty}(\\frac{x^2}{(x-a)(x+b)})^x的思路?", "原式变为\\lim_{x\\to\\infty}(\\frac{x}{x-a})^x(\\frac{x}{x+b})^x \\\\ \\lim_{x\\to\\infty}\\frac{1}{(1-\\frac{a}{x})^x}\\frac{1}{(1+\\frac{b}{x})^x} = e^{a-b} "],
        ["\\lim_{n\\to\\infty}\\frac{n^{n+1}}{(n+1)^n}\\sin\\frac{1}{n}的思路?", "原式变为(\\frac{n}{n+1})^n n\\sin\\frac{1}{n} \\\\ n\\to\\infty, \\frac{1}{n}\\to 0, 等价代换后n\\sin\\frac{1}{n}=1 \\\\ 左边上下除n得\\frac{1}{(1+\\frac{1}{n})^n} \\\\ 极限值为 e^{-1}"],
        ["若\\lim a(x)=0, \\lim b(x)=\\infty \\\\ 且\\lim a(x)b(x)=A \\\\ 那 \\lim (1+a(x))^{b(x)}=?", "\\lim (1+a(x))^{b(x)}=e^A"],
        ["\\lim_{x\\to 0}\\frac{a^x-1}{x}=?", "\\lim_{x\\to 0}\\frac{a^x-1}{x}=\\ln(a)"],
        ["x\\to 0时,\\frac{1}{x^2}\\sin\\frac{1}{x}是无穷大吗", "令a=\\frac{1}{2n\\pi+\\frac{\\pi}{2}}, 使得代入后\\sin\\frac{1}{x}=1 \\\\ 令b=\\frac{1}{2n\\pi}, 使得代入后\\sin\\frac{1}{x}=0 \\\\  则对于任意的M>0,都有\\delta>0 \\\\ 0<a<\\delta 和 0<b<\\delta \\\\ 代入a = (2n\\pi+\\frac{\\pi}{2})^2>M, 代入b得0 \\\\ 所以是无界的，但不是无穷大"],
        ["已知\\lim_{n\\to\\infty}x_n=a,下面是否成立\\\\ \\lim_{n\\to\\infty}x_{2n}=\\lim_{n\\to\\infty}x_{2n+1}=a \\\\ \\lim_{n\\to\\infty}x_{3n}=\\lim_{n\\to\\infty}x_{3n+1}=a \\\\ 返过来可以吗", "若数列极限为a \\\\ 那么它的任意部分列极限都为a \\\\ 若已知 x_{2n} 和 x_{2n+1} (奇数列和偶数列) \\\\ 极限为a,可以推出x_n极限也为a \\\\ 但是x_{3n}和x_{3n+1}不行, 它没覆盖所有的x_n \\\\ 若加上x_{3n+2}也为a,则可推出x_n=a"],
        ["若\\lim\\frac{a(x)}{[b(x)]^k}=C\\ne0", "a(x)是b(x)的k阶无穷小 \\\\ x\\to0, x^{100}是x的100阶无穷小"],
        ["a(x)\\to0, b(x)\\to0 \\\\ \\lim\\frac{a(x)}{b(x)}=L \\\\ L=\\infty代表什么, L=C代表什么 \\\\ L=1代表什么", "L=\\infty 代表a(x)是b(x)的低阶无穷小 \\\\ L=C 代表a(x)是b(x)的同阶无穷小 \\\\ L=1 代表a(x)和b(x)是等价无穷小"],
        ["a(x)\\to0, b(x)\\to0 \\\\ \\lim\\frac{a(x)}{b(x)}=0, 则?", "a(x)=o(b(x)) \\\\ a(x)趋向0的速度比b(x)快 \\\\ a(x)是b(x)的高阶无穷小"],
        ["\\lim_{n\\to\\infty}\\frac{2^n}{n!}", "0<\\frac{2^n}{n!}=\\frac{2*2*2*...*2}{1*2*3*...*n}\\le\\frac{4}{n} \\\\ n\\to\\infty, 两边都为0 \\\\ 解法2: a_n = \\frac{2^n}{n!}, a_{n+1} = \\frac{2}{n+1}a_n \\\\ 单调有界函数\\to有极限,假设\\lim_{n\\to\\infty}a_n = A \\\\ 两边取极限 A=0*A, A=0"],
        ["取整函数[x](向下)的基本不等式", "[x]定义是不大于x的最大整数 \\\\ 所以[x]\\le x (=是x为整数的情况) \\\\ [x]在舍去小数时，最大不会超过1 \\\\ 所以x-1<[x]\\le x"],
        ["\\lim_{n\\to\\infty}[\\frac{n}{n^2+1}+\\frac{n}{n^2+2}+...+\\frac{n}{n^2+n}]", "这道题的思路是用夹逼定理 \\\\ 把分母都换成n^2+n，分子加起来=n^2 \\\\ 所以 \\frac{n^2}{n^2+n} \\le [原式] \\le \\frac{n^2}{n^2+1} \\\\ n\\to\\infty时,两边都为1,所以极限为1"],
        ["\\lim_{n\\to\\infty}[\\frac{n}{n^2+1}+\\frac{n}{n^2+2}+...+\\frac{n}{n^2+n}] \\\\ 等于0吗?", "这里看似\\frac{n}{n^2+1}=0 \\\\ 极限就是很多0加起来，所以等于零 \\\\ 但这个思路是错的，这里有无限项 \\\\ 不能这么加"],
        ["单调有界数列必有极限", "单调增、有上界的数列必有极限 \\\\ 单调减、有下界的数列必有极限"],
        ["函数保号性 \\\\ 设\\lim_{x\\to x_0}f(x)=A \\\\ 若存在\\delta>0,当x\\in\\mathring{U}(x_0,\\delta)时 \\\\ f(x)\\ge0(或f(x)\\le0)", "A\\ge 0(或A\\le 0)"],
        ["函数保号性 \\\\ 设\\lim_{x\\to x_0}f(x)=A", "若A>0(或A<0),则存在\\delta>0 \\\\ 当x\\in\\mathring{U}(x_0,\\delta)时 \\\\ f(x)>0(或f(x)<0)"],
        ["\\mathring{U}(x_0,\\delta)是什么?", "以x_0为中心,\\delta为半径的一个去心邻域"],
        ["存在N>0,当n>N,x_n\\ge0(或x_n\\le0) \\\\ 则x_n的极限A有什么性质?", "A\\ge0(或A\\le0) \\\\ 保号性，极限的符号与N项后的x_n的符号相同"],
        ["保号性", "设\\lim_{n\\to\\infty}x_n=A \\\\ 若A>0(或A<0),则存在N>0 \\\\ 当n>N时,x_n>0(或x_n<0) \\\\ 若数列的极限不为0 \\\\ N项后的x_n与极限符号相同"],
        ["若数列收敛,那它有界吗?", "数列收敛必有界 \\\\ 但有界的数列不一定收敛 \\\\ 例:(-1)^n (极限不存在) \\\\ 如果数列有界且单调,那它收敛"],
        ["数列{x_n}收敛的定义?", "数列收敛就是n\\to\\infty, x_n的极限存在 \\\\ 极限存在(不能为正负无穷)"],
        ["\\lim_{x\\to0}(1+|x|)^{\\frac{1}{x}}=?","\\lim_{x\\to0^-}(1+(-1)*x)^{\\frac{1}{x}}=e^{-1} \\\\ \\lim_{x\\to0^+}(1+x)^{\\frac{1}{x}}=e"],
        ["\\lim_{x\\to 0}e^{\\frac{1}{x}} = ? \\\\ \\lim_{x\\to \\infty}e^x=? \\\\ \\lim_{x\\to \\infty}e^{-x} =?","\\lim_{x\\to 0}e^{\\frac{1}{x}} 不存在 \\\\ \\lim_{x\\to \\infty}e^x 不存在 \\\\ \\lim_{x\\to \\infty}e^{-x} 不存在 \\\\ 要特别注意左右极限的相等"],
        ["\\lim_{x\\to a}f(x)=A的数学定义","\\forall\\epsilon>0,\\exists\\delta>0 \\\\ 当0<|x-a|<\\delta时,恒有|f(x)-A|<\\epsilon \\\\ 0<|x-a|<\\delta是个关于a的去心邻域 \\\\ 所以f(x)在a处可以没定义"],
        ["n\\to\\infty实际上是什么?","n一般指代下标 \\\\ 所以n\\to\\infty 约定为 n\\to+\\infty"],
        ["\\lim_{x\\to\\infty} \\frac{\\sqrt{x^2+1}}{x}=?","x \\to \\infty 代表正负无穷都要考虑 \\\\ \\lim_{x\\to\\infty} \\frac{|x|\\sqrt{1+\\frac{1}{x^2}}}{x} \\\\ 此极限趋正无穷时=1, 趋负无穷时=-1 \\\\ 正负无穷不一样,极限不存在"],
        ["\\lim_{x\\to-\\infty}f(x)=A 的数学定义 ","\\forall\\epsilon>0,\\exists\\delta>0,当x<-\\delta时 \\\\ 恒有|f(x)-A|<\\epsilon"],
        ["\\lim_{x\\to+\\infty}f(x)=A 的数学定义 ","\\forall\\epsilon>0,\\exists\\delta>0,当x>\\delta时 \\\\ 恒有|f(x)-A|<\\epsilon"],
    ]
}