export default {
    name: "arc",
    cards: [
        ["\\text{graph of: } \\csc^{-1}(x)", "image:math_arccsc_graph.png"],
        ["\\text{graph of: } \\cot^{-1}(x)", "image:math_arccot_graph.png"],
        ["\\text{graph of: } \\tan^{-1}(x)", "image:math_arctan_graph.png"],
        ["\\text{graph of: } \\cos^{-1}(x)", "image:math_arccos_graph.png"],
        ["\\text{graph of: } \\sin^{-1}(x)", "image:math_arcsin_graph.png"],
        ["\\text{graph of: } \\sec^{-1}(x)", "image:math_arcsec_graph.png"],
        ["\\tan^{-1}(x)的奇偶性和定义域", "奇函数,R, (-\\frac{\\pi}{2}, \\frac{\\pi}{2})"],
        ["\\cos^{-1}(x)的奇偶性和定义域", "无奇偶,[-1, 1], [0, \\pi]"],
        ["\\sin^{-1}(x)的奇偶性和定义域", "奇函数, [-1, 1], [-\\frac{\\pi}{2}, \\frac{\\pi}{2}]"],
        ["\\cot^{-1}(x)的奇偶性和定义域", "无奇偶,R,(0,\\pi)"],
        ["\\csc^{-1}(x)的奇偶性和定义域", "奇函数,(-\\infty, -1] \\cup [1, \\infty) \\\\ [-\\frac{\\pi}{2},\\frac{\\pi}{2}] \\setminus \\{0\\}"],
        ["\\sec^{-1}(x)的奇偶性和定义域", "无奇偶,(-\\infty, -1] \\cup [1, \\infty) \\\\ [0,\\pi] \\setminus \\{\\frac{\\pi}{2}\\}"],
        ["\\frac{d}{dx}\\csc^{-1}(x)=?", "-\\frac{1}{|x|\\sqrt{x^2-1}}"],
        ["\\frac{d}{dx}\\tan^{-1}(x)=?", "\\frac{1}{1+x^2}"],
        ["\\frac{d}{dx}\\cot^{-1}(x)=?", "-\\frac{1}{1+x^2}"],
        ["\\frac{d}{dx}\\cos^{-1}(x)=?", "-\\frac{1}{\\sqrt{1-x^2}}"],
        ["\\frac{d}{dx}\\sin^{-1}(x)=?", "\\frac{1}{\\sqrt{1-x^2}}"],
        ["\\frac{d}{dx}\\sec^{-1}(x)=?", "\\frac{1}{|x|\\sqrt{x^2-1}}"],
        ["\\lim_{x \\to -\\infty}\\sec^{-1}(x)=?", "\\frac{\\pi}{2}"],
        ["\\lim_{x \\to \\infty}\\sec^{-1}(x)=?", "\\frac{\\pi}{2}"],
        ["\\lim_{x \\to \\infty}\\csc^{-1}(x)=?", "0"],
        ["\\lim_{x \\to -\\infty}\\csc^{-1}(x)=?", "0"],
        ["\\lim_{x \\to \\infty}\\cot^{-1}(x)=?", "0"],
        ["\\lim_{x \\to -\\infty}\\cot^{-1}(x)=?", "\\pi"],
        ["\\lim_{x \\to -\\infty}\\tan^{-1}(x)=?", "-\\frac{\\pi}{2}"],
        ["\\lim_{x \\to \\infty}\\tan^{-1}(x)=?", "\\frac{\\pi}{2}"],
        ["\\sin^{-1}(x) + \\cos^{-1}(x)=?", "\\frac{\\pi}{2}"],
    ]
}