export default {
    name: "calc",
    cards: [
        [
            "水平渐近线", "\\lim _{x\\to \\infty }f\\left(x\\right)=A \\\\ y=A就是一个水平渐近线",
            "垂直渐近线", "\\lim _{x\\to x_0 }f\\left(x\\right)=\\infty \\\\ x=x_0就是一个垂直渐近线",
            "斜渐近线的定义", "\\lim _{x\\to \\infty }\\frac{f\\left(x\\right)}{x}=a \\\\ \\lim _{x\\to \\infty }\\left(f\\left(x\\right)-ax\\right)=b \\\\ 那么y=ax+b是y=f(x)的斜渐近线",
            "一个求斜渐近线更快的方法", "如果f(x)能写成 ax+b+g(x)形式 \\\\ 且x\\to\\infty,g(x)\\to0 \\\\ 那么y=ax+b就是f(x)的一个斜渐近线 \\\\ 这里的\\infty不用正负都趋向零 \\\\ 一边趋向0就是有斜渐近线",
        ],
        ["若f(x)可导，那其反函数的导数是什么?", "若y=f(x)可导,且f'(x)\\ne0 \\\\ 其反函数x=\\phi(y)也可导 \\\\ \\phi'(y)=\\frac{1}{f'(x)} \\\\ f'(x)是切线关于x轴夹角\\alpha的\\tan \\alpha值 \\\\ \\phi'(y)是关于y轴夹角\\beta的\\tan \\beta值 \\\\ \\beta = \\frac{\\pi}{2}-\\alpha, 所以两者\\tan互为倒数", "image:math_inverse_derivative_explain.png"],
        ["导数的定义",
            "f'\\left(x_0\\right)=\\lim _{\\triangle x\\to 0}\\frac{f\\left(x_0+\\triangle x\\right)-f\\left(x_0\\right)}{\\triangle x} \\\\ f'\\left(x_0\\right)=\\lim _{\\triangle x\\to x_0}\\frac{f\\left(x\\right)-f\\left(x_0\\right)}{x-x_0}",
            "左右导数的定义",
            "左导数:f_-'\\left(x_0\\right)=\\lim _{\\triangle x\\to 0^-}\\frac{f\\left(x_0+\\triangle x\\right)-f\\left(x_0\\right)}{\\triangle x} \\\\ 右导数: f_+'\\left(x_0\\right)=\\lim _{\\triangle x\\to 0^+}\\frac{f\\left(x_0+\\triangle x\\right)-f\\left(x_0\\right)}{\\triangle x}"  ,
            "可导的定义",
            "text:点A可导$\\iff$点A左右导数存在且相等 \n 在区间[a,b]上可导:在(a,b)每一点都可导 \n 且左端点处有右导数，右端点处有左导数 \n 则称函数f(x)在[a,b]上可导",
        ],
        ["\\lim _{n\\to \\infty }a^{\\frac{1}{n}}=\\lim _{n\\to \\infty }\\sqrt[n]{a}=?", "\\lim _{n\\to \\infty }a^{\\frac{1}{n}}=\\lim _{n\\to \\infty }\\sqrt[n]{a}=1(a>0)",
            "\\lim _{n\\to \\infty }n^{\\frac{1}{n}}=\\lim _{n\\to \\infty }\\sqrt[n]{n}=?", "\\lim _{n\\to \\infty }n^{\\frac{1}{n}}=\\lim _{n\\to \\infty }\\sqrt[n]{n}=1"
        ],
        ["image:math_infinite_small_2_ques.png", "image:math_infinite_small_2_ans.png",
            "image:math_infinite_small_1_ques.png", "image:math_infinite_small_1_ans.png"
        ],
        ["证明方程根存在和个数，一般用什么定理", "证明方程根存在,用零点定理、罗尔定理 \\\\ 证明方程根个数，用单调性"],
        ["连续的定义 \\\\ \\lim_{\\triangle x\\to0}\\triangle y=?",
            "\\lim _{\\triangle x\\to 0}\\triangle y=\\lim _{\\triangle x\\to 0}\\left[f\\left(x_0+\\triangle x\\right)-f\\left(x_0\\right)\\right]=0 \\\\ 当x的改变量趋于0时，函数值的改变量也趋于0",
            "\\lim _{x\\to x_0^+}f\\left(x\\right)=f\\left(x_0\\right) \\\\ 则称?",
            "若\\lim _{x\\to x_0^+}f\\left(x\\right)=f\\left(x_0\\right) \\\\ 则称f(x)在x_0点处右连续 \\\\ f\\left(x\\right)连续\\Leftrightarrow f\\left(x\\right)左连续且右连续",
            "\\lim _{x\\to x_0^-}f\\left(x\\right)=f\\left(x_0\\right) \\\\ 则称?",
            "若\\lim _{x\\to x_0^-}f\\left(x\\right)=f\\left(x_0\\right) \\\\ 则称f(x)在x_0点处左连续 \\\\ f\\left(x\\right)连续\\Leftrightarrow f\\left(x\\right)左连续且右连续",
            "f(x) 在[a,b]上连续的定义",
            "若f(x)在(a,b)上的每一点都连续 \\\\ 且f(x)在a点处右连续，在b点处左连续 \\\\ 则称函数f(x)在[a,b]上连续",
            "间断点的定义",
            "若f(x)在x_0某去心领域有定义 \\\\ 但在x_0处不连续 \\\\ 则称x_0为f(x)的间断点",
            "第一类间断点",
            "左右极限都存在的间断点 \\\\ 可去间断点：左极限=右极限 \\\\ 跳跃间断点：左极限\\ne右极限",
            "第二类间断点",
            "左右极限中至少有一个不存在 \\\\ 无穷间断点：x\\to0, f(x)=\\frac{1}{x} \\\\ 振荡间断点：x\\to0, f(x)=\\sin(\\frac{1}{x})"
        ],
        ["单调有界数列必有极限", "单调增、有上界的数列必有极限 \\\\ 单调减、有下界的数列必有极限"],
        ["若数列收敛,那它有界吗?", "数列收敛必有界 \\\\ 但有界的数列不一定收敛 \\\\ 例:(-1)^n (极限不存在) \\\\ 如果数列有界且单调,那它收敛"],
        ["数列{x_n}收敛的定义?", "数列收敛就是n\\to\\infty, x_n的极限存在 \\\\ 极限存在(不能为正负无穷)"],

        ["\\lim_{x\\to a}f(x)=A的数学定义",
            "\\forall\\epsilon>0,\\exists\\delta>0 \\\\ 当0<|x-a|<\\delta时,恒有|f(x)-A|<\\epsilon \\\\ 0<|x-a|<\\delta是个关于a的去心邻域 \\\\ 所以f(x)在a处可以没定义",
            "\\lim_{x\\to-\\infty}f(x)=A 的数学定义 ",
            "\\forall\\epsilon>0,\\exists\\delta>0,当x<-\\delta时 \\\\ 恒有|f(x)-A|<\\epsilon",
            "\\lim_{x\\to+\\infty}f(x)=A 的数学定义 ",
            "\\forall\\epsilon>0,\\exists\\delta>0,当x>\\delta时 \\\\ 恒有|f(x)-A|<\\epsilon",
        ],
        ["高阶导数的定义",
            "f^{\\left(n\\right)}\\left(x_0\\right)=\\lim _{\\triangle x\\to 0}\\frac{f^{\\left(n-1\\right)}\\left(x_0+\\triangle x\\right)-f^{\\left(n-1\\right)}\\left(x_0\\right)}{\\triangle x} \\\\ f^{\\left(n\\right)}\\left(x_0\\right)=\\lim _{x\\to x_0}\\frac{f^{\\left(n-1\\right)}\\left(x\\right)-f^{\\left(n-1\\right)}\\left(x_0\\right)}{x-x_0}",
            "\\frac{d^n\\left(uv\\right)}{dx^n}=?",
            "\\frac{d^n\\left(uv\\right)}{dx^n}=\\sum _{k=0}^nC_n^k\\cdot \\frac{d^k\\left(u\\right)}{dx^k}\\frac{d^{n-k}\\left(v\\right)}{dx^{n-k}}",
            "\\frac{d^n\\left(u\\pm v\\right)}{dx^n}=?",
            "\\frac{d^n\\left(u\\pm v\\right)}{dx^n}=\\frac{d^n\\left(u\\right)}{dx^n}\\pm \\frac{d^n\\left(v\\right)}{dx^n}",
            "\\frac{d^n\\left(\\cos x\\right)}{dx^n}=?",
            "\\frac{d^n\\left(\\cos x\\right)}{dx^n}=\\cos \\left(x+n\\cdot \\frac{\\pi }{2}\\right)",
            "\\frac{d^n\\left(\\sin x\\right)}{dx^n}=?",
            "\\frac{d^n\\left(\\sin x\\right)}{dx^n}=\\sin \\left(x+n\\cdot \\frac{\\pi }{2}\\right)",
        ],

        ["保号性的定义 \\\\ 设\\lim_{x\\to x_0}f(x)=A \\\\ 设\\lim_{n\\to\\infty}x_n=A \\\\ (两个A并不相同，只是一个符号) \\\\ (翻页)",
            "若存在\\delta>0,当x\\in\\mathring{U}(x_0,\\delta)时 \\\\ f(x)\\ge0(或f(x)\\le0)",
            "那么 A\\ge 0(或A\\le 0)",
            "若A>0(或A<0),则存在\\delta>0",
            "当x\\in\\mathring{U}(x_0,\\delta)时 \\\\ f(x)>0(或f(x)<0)",
            "存在N>0,当n>N,x_n\\ge0(或x_n\\le0)",
            "A\\ge0(或A\\le0)",
            "若A>0(或A<0),则存在N>0",
            "当n>N时,x_n>0(或x_n<0) \\\\ 若数列的极限不为0 \\\\ N项后的x_n与极限符号相同"
        ],

        ["\\lim \\frac{f\\left(x\\right)}{g\\left(x\\right)}中,\\lim g(x)\\to0 \\\\ 分母趋向0,那在什么条件下分子也趋0",
            "\\lim \\frac{f\\left(x\\right)}{g\\left(x\\right)}=A \\\\ 极限存在,分母趋向0,分子也趋0",
            " 证明: \\\\ \\lim f(x) = \\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\cdot g\\left(x\\right)\\right) =0 \\\\ 那么\\lim f(x)也\\to0 ",
            "\\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\right)中,\\lim f\\left(x\\right)\\to 0 \\\\ 分子趋向0,那在什么条件下分母也趋0",
            "\\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\right)=A\\ne0 \\\\ 极限存在，且不为0的情况下 \\\\ 分子趋向0,分母也趋向0",
            "\\lim g\\left(x\\right)=\\lim \\left(\\frac{g\\left(x\\right)}{f\\left(x\\right)}\\cdot f\\left(x\\right)\\right) \\\\ =\\lim \\left(\\frac{g\\left(x\\right)}{f\\left(x\\right)}\\right)\\lim \\left(f\\left(x\\right)\\right) \\\\ =\\frac{1}{\\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\right)}\\lim \\left(f\\left(x\\right)\\right) \\\\ 已知 \\lim \\left(\\frac{f\\left(x\\right)}{g\\left(x\\right)}\\right)=A\\ne 0 \\\\ \\therefore \\lim g(x)=\\frac{1}{A}\\cdot 0=0"
        ],
        ["幂指函数求极限的作法 \\\\ \\lim_{x\\to0}(\\frac{2+\\cos x}{3})^x-1", "将幂指函数改写为e^{\\ln(...)}, 再用e^x-1 \\sim x 代换 \\\\ \\lim_{x\\to0}e^{x\\ln(\\frac{2+\\cos x}{3})}-1, e的指数趋于0,可以代换 \\\\ \\lim_{x\\to0}x\\ln(\\frac{2+\\cos x}{3})"],
        ["等价无穷小代换原则", "乘除可以换, 若a\\sim a_1, b\\sim b_1 \\\\ 且 \\lim \\frac{a_1}{b_1}=A\\ne1 则减法可以换 \\\\ a-b \\sim a_1-b_1 \\\\ 若 \\lim \\frac{a_1}{b_1}=A\\ne-1 则加法可以换 \\\\ a+b \\sim a_1+b_1  "],
        ["a^x-1的等价无穷小", "a^x-1 \\sim x\\ln(a)"],
        ["求曲线f(x)在点(x_0,f(x_0))的切线方程", "切线方程:y-f(x_0)=f'(x_0)(x-x_0) \\\\ 法线方程:y-f(x_0)=-\\frac{1}{f'(x_0)}(x-x_0)"],
        ["设f\\left(x\\right)=\\phi \\left(x\\right)\\left|x-a\\right| \\\\ 其中\\phi(x)在x=a处连续 \\\\ 则f(x)在x=a处可导的充要条件是?", "\\phi(a)=0"],
        ["参数方程求导", "image:math_parametric_function_derivative.png"],
        ["若f(x)可导，f'(x)的奇偶性如何?", "若f(x)可导 \\\\ 且f(x)为奇函数, 那么f'(x)为偶函数 \\\\ 若f(x)为偶函数,那么f'(x)为奇函数 \\\\ 若f(x)为周期函数,那么f'(x)也为周期函数"],
        ["f(x)在x_0的某邻域可导,能推出: \\\\ f'(x)在x_0点处连续 \\\\ \\lim_{x\\to x_0} f'(x)存在吗?", "f(x)在x_0的某领域可导 \\\\ 推不出f'(x)在x_0点处连续 \\\\ 也推不出 \\lim_{x\\to x_0} f'(x)存在"],
        ["连续、可导、可微之间的关系", "image:math_relation_c_d.png"],
        ["曲率的定义", "曲率K=\\frac{\\left|y''\\right|}{\\left(1+\\left(y'\\right)^2\\right)^{\\frac{3}{2}}} \\\\ 曲率半径R=\\frac{1}{K}"],
        ["设(x_0, f(x_0))是拐点 \\\\ 能说x_0是函数的拐点吗?", "不能，拐点要把x,y都写上"],
        ["什么是驻点?", "导数为0的点"],
        ["什么时候用泰勒公式?\\\\用皮亚诺余项还是拉格朗日余项?\\\\在哪一点上用?", "text:1.只要题目中出现n阶导的形式,要想到泰勒 \n 2.研究局部(极限,极值)用皮亚诺 \n 3.研究整体(最值,不等式)用拉格朗日 \n 4.哪一点提供的信息多,就在哪点用"],
        ["若f(x)在[a,b]上连续，那它有界吗?","若f(x)在[a,b]上连续 \\\\ 则f(x)在[a,b]上有界"],
        ["初等函数是连续的吗?","初等函数由初等基本函数 \\\\ 经过有限次的复合得到 \\\\ 初等函数在其定义区间内连续 \\\\ 注意这里说的是定义区间，而不是定义域 \\\\ 例: \\sqrt{\\cos(x)-1} 的定义域为离散的点 \\\\ 离散的点无从谈起连续，都是离散的点也没有定义区间"],
        ["连续函数的复合是连续的吗？","连续函数的复合仍为连续函数"],
        ["连续函数的和、差、积、商仍为连续函数吗？","连续函数的和、差、积、商仍为连续函数! \\\\ 商分母不为0"],
        ["如何判断拐点", "f''(c)=0, 两侧变号 \\\\ 或f''(c)=0, f'''(c)\\ne0"],
        ["极限为指数时使用洛必达", "若f(x)=g(x)^{m(x)}, 可将其改写为\\ln形式 \\\\ f(x)=e^{m(x)\\ln[g(x)]}, 这样就化为了乘法 \\\\ 可以尝试把一个因子放到分母上 \\\\ f(x)=e^{\\frac{\\ln[g(x)]}{\\frac{1}{m(x)}}}, 就可以尝试用洛必达了"],

        ["洛必达法则的适用情况", "\\frac{0}{0}, \\frac{\\infty}{\\infty}, 若不是这个形式 \\\\ 可以尝试通分, 取对数, 等方式转化"],
        ["牛顿法近似 \\\\ a是f(x)=0的一个近似", "b=a-\\frac{f(a)}{f'(a)}"],
        ["f在x=a处的微分", "df=f'(a)\\triangle x"],
        ["f(a+\\triangle x)\\approx", "f(a)+f'(a)\\triangle x"],
        ["线性化方程L(x)", "L(x)=f(a)+f'(a)(x-a)"],
        ["0 * \\infty时使用洛必达", "化成\\frac{\\infty}{\\frac{1}{0}}的形式, 即  (\\frac{\\infty}{\\infty})"],
        ["\\infty - \\infty时使用洛必达", "想办法通分成\\frac{0}{0}或\\frac{\\infty}{\\infty}的形式"],
        ["f''(x)的正负代表什么？", "f''(x)>0代表函数凹向上 \\\\ f''(x)<0代表函数凹向下"],
        ["二阶导如何判断f'(a)=0的类型", "f''(a)>0=局部最小值 \\\\ f''(a)<0=局部最大值 \\\\ f''(a)=0 无法判断 "],
        ["一阶导如何判断f'(a)=0的类型", "从左往右通过a点: \\\\ f'(x)从负到正=局部最小值 \\\\ f'(x)从正到负=局部最大值 \\\\ f'(x)符号不变=拐点 "],
        ["f'(a)=0代表什么？", "text:a点可能是f(x)的局部最大值、局部最小值，或拐点"],
    ]
}
