export default {
    name: "integral",
    cards: [
        ["\\int_{-a}^{a}f(x)dx=?", "如果f(x)是奇函数的话，积分值等于0 \\\\ 如果f(x)是偶函数，积分等于2\\int_0^{a}f(x)dx", "image:math_2023-08-18-05-45-50.png"],
        ["\\int_{a}^{b}(f(x)+g(x))dx=?", "\\int_{a}^{b}f(x)dx + \\int_{a}^{b}g(x)dx"],
        ["\\int_{a}^{b}Cf(x)dx=?", "C\\int_{a}^{b}f(x)dx=?"],
        ["\\int_{a}^{c}f(x)dx + \\int_{c}^{b}f(x)dx = ?", "\\int_{a}^{b}f(x)dx"],
        ["\\int_{a}^{a}f(x)dx=?", "0"],
        ["\\int_{a}^{b}f(x)dx=(\\text{what})\\int_{b}^{a}f(x)dx", "\\int_{a}^{b}f(x)dx=(-1)\\int_{b}^{a}f(x)dx"],

        ["f(x)在什么条件下，一定存在原函数?", "若f(x)在I上连续，则区间I上一定存在原函数",
            "f(x)在什么条件下，一定没有原函数?", "若f(x)在区间I上有第一类间断点 \\\\ 则f(x)在I上没有原函数"
        ],
        ["t=\\tan \\frac{x}{2} \\\\ dx=? \\sin x=? \\cos x=?", "x = 2\\arctan t \\\\ dx=\\frac{2}{1+t^2}dt, \\sin x = \\frac{2t}{1+t^2} \\\\ \\cos x=\\cos x=\\frac{1-t^2}{1+t^2}", "\\sin x=\\frac{2\\sin \\frac{x}{2}\\cos \\frac{x}{2}}{\\sin ^2\\frac{x}{2}+\\cos ^2\\frac{x}{2}} \\\\ 上下同除\\cos\\frac{x}{2} \\\\ \\sin x=\\frac{2\\tan \\frac{x}{2}}{1+\\tan ^2\\frac{x}{2}}=\\frac{2t}{1+t^2}"],
        ["常见的积不出函数", "\\int e^{x^2}dx,\\int \\frac{\\sin x}{x}dx,\\int \\frac{\\cos x}{x}dx \\\\ 碰到这些函数要知道，它们的原函数不是初等函数"],
        ["\\int \\csc(x)dx=?", "\\int \\csc xdx=-\\ln \\left|\\csc x+\\cot x\\right|+C"],
        ["\\int \\sec(x)dx=?", "\\int \\sec xdx=\\ln \\left|\\sec x+\\tan x\\right|+C"],
        ["\\int \\frac{dx}{\\sqrt{x^2-a^2}}=?", "\\int \\frac{dx}{\\sqrt{x^2-a^2}}=\\ln \\left|x+\\sqrt{x^2-a^2}\\right|+C"],
        ["\\int \\frac{dx}{\\sqrt{x^2+a^2}}=?", "\\int \\frac{dx}{\\sqrt{x^2+a^2}}=\\ln \\left|x+\\sqrt{x^2+a^2}\\right|+C"],
        ["\\int \\frac{1}{x^2-a^2}dx=?", "\\int \\frac{1}{x^2-a^2}dx=\\frac{1}{2a}\\ln \\left|\\frac{x-a}{x+a}\\right|+C"],
        ["\\int \\frac{1}{\\sqrt{a^2-x^2}}dx=?", "\\int \\frac{1}{\\sqrt{a^2-x^2}}dx=\\arcsin \\left(\\frac{x}{a}\\right)+C"],
        ["如何用定积分的定义求极限","1.提出\\frac{1}{n},把变化的地方写成x \\\\ 2.看变化的地方的极限，写出上下限 \\\\ 3.确认\\frac{1}{n}是否准确，是否要补项"],
        ["定积分的定义","\\lim _{n\\to \\infty }\\frac{1}{n}\\sum _{i=1}^nf\\left(\\frac{i}{n}\\right)=\\int _0^1f\\left(x\\right)dx \\\\ 基中n是将图形切分的份数,n越大,越精确"],
        ["\\frac{d}{dx} \\ln|x|","\\frac{1}{x}"],
        ["曲线绕y轴旋转的体积:","\\int_{a}^b 2\\pi xydx"],
        ["曲线绕x轴旋转的体积:","\\int_{a}^b \\pi y^2dx"],
        ["\\sqrt{x^2-a^2}, 三角替换", "x=a\\sec(\\theta) \\\\ x^2-a^a=a^2\\tan^2(\\theta) \\\\ 考虑绝对值, x<0时, 对边为负 "],
        ["\\sqrt{a^2+x^2}, 三角替换", "x=a\\tan(\\theta) \\\\ a^2+x^2=a^2\\sec^2(\\theta)"],
        ["\\sqrt{a^2-x^2}, 三角替换", "x=a\\sin(\\theta) \\\\ a^2-x^2=a^2\\cos^2(\\theta)"],
        ["\\int b^xdx=?", "\\frac{b^x}{ln(b)}+C"],
        ["\\int x^adx=?(a \\neq 1)", "\\frac{x^{a+1}}{a+1}+C"],
        ["\\int \\frac{1}{t^2+a^2}dt=?", "\\frac{1}{a} tan^{-1}(\\frac{t}{a}) + C"],
        ["\\frac{...}{(...)(x+a)^3},怎么拆", "... + \\frac{A}{(x+a)^3} + \\frac{B}{(x+a)^2} + \\frac{C}{(x+a)}"],
        ["\\frac{...}{(...)(x^2+ax+b)},怎么拆", "... + \\frac{Ax+B}{x^2+ax+b}"],
        ["\\frac{...}{(...)(x+a)^2},怎么拆", "... + \\frac{A}{(x+a)^2} + \\frac{B}{(x+a)}"],
        ["\\frac{...}{(...)(x+a)},怎么拆", "... + \\frac{A}{(x+a)}"],
        ["分部积分法", "\\int udv = uv - \\int vdu"],
        ["\\int \\frac{f'(x)}{f(x)}dx=?", "ln|f(x)| + C"],
        ["\\int_{a}^{b}f(x)dx=? \\\\ F(x)是f的任意反导数", "F(b)-F(a)"],
        ["\\frac{d}{dx}\\int_{a}^{x}f(t)dt=?", "f(x)"],
    ]
}
