export default {
    name: "trig",
    cards: [
        ["\\sin(A)\\cos(B)", "\\frac{1}{2}(\\sin(A-B)+\\sin(A+B))"],
        ["\\sin(A)\\sin(B)", "\\frac{1}{2}(\\cos(A-B)-\\cos(A+B))"],
        ["\\cos(A)\\cos(B)", "\\frac{1}{2}(\\cos(A-B)+\\cos(A+B))"],
        ["\\cos(2x)=?", "\\displaylines{\\cos^2(x)-\\sin^2(x) \\\\ 1-2\\sin^2(x) \\\\ 2\\cos^2(x)-1 \\\\ \\frac{1-\\tan^2(x)}{1+\\tan^2(x)}}"],
        ["\\sin(2x)=?", "2\\sin(x)\\cos(x)"],
        ["\\sin^2(x)=?", "\\frac{1}{2}(1-\\cos(2x))"],
        ["\\cos^2(x)=?", "\\frac{1}{2}(1+\\cos(2x))"],
        ["描述三角函数的奇偶性", "\\cos和\\sec为偶函数，其余为奇"],
        ["\\frac{d}{dx}\\sinh(x)=?", "\\cosh(x)"],
        ["\\frac{d}{dx}\\cosh(x)=?", "\\sinh(x)"],
        ["\\cosh^2(x)-\\sinh^2(x)=?", "1"],
        ["\\sinh(x)=?", "\\frac{e^x-e^{-x}}{2}"],
        ["\\cosh(x)=?", "\\frac{e^x+e^{-x}}{2}"],
        ["\\sin(\\frac{π}{6})", "\\frac {1}{2}"],
        ["\\sin(0)", "0"],
        ["\\sin(\\frac{π}{4})", "\\frac{\\sqrt{2}}{2}"],
        ["\\sin(\\frac{π}{3})", "\\frac{\\sqrt{3}}{2}"],
        ["\\sin(\\frac{π}{2})", "1"],
        ["\\cos(0)", "1"],
        ["\\cos(\\frac{π}{6})", "\\frac{\\sqrt{3}}{2}"],
        ["\\cos(\\frac{π}{4})", "\\frac{\\sqrt{2}}{2}"],
        ["\\cos(\\frac{π}{3})", "\\frac{1}{2}"],
        ["\\cos(\\frac{π}{2})", "0"],
        ["\\tan(0)", "0"],
        ["\\tan(\\frac{π}{6})", "\\frac{\\sqrt{3}}{3}"],
        ["\\tan(\\frac{π}{4})", "1"],
        ["\\tan(\\frac{π}{3})", "\\sqrt{3}"],
        ["\\tan(\\frac{π}{2})", "DNE"],
        ["\\sin 定义", "\\frac{y}{r} \\frac{对}{斜}"],
        ["\\cos 定义", "\\frac{x}{r} \\frac{邻}{斜}"],
        ["\\tan 定义", "\\frac{y}{x} \\frac{对}{邻}"],
        ["\\cot 定义", "\\frac{x}{y} \\frac{邻}{对}"],
        ["\\sec 定义", "\\frac{r}{x} \\frac{斜}{邻}"],
        ["\\csc 定义", "\\frac{r}{y} \\frac{斜}{对}"],
        ["\\tan和\\sin,\\cos的关系", "\\tan=\\frac{\\sin}{\\cos}"],
        ["\\cot和\\sin,\\cos的关系", "\\cot=\\frac{\\cos}{\\sin}"],
        ["\\sin(A+B)", "\\sin{A}\\cos{B} + \\sin{B}\\cos{A}"],
        ["\\cos(A+B)", "\\cos{A}\\cos{B} - \\sin{A}\\sin{B}"],
        ["\\cos^2(x)+\\sin^2(x)", "1"],
        ["1+\\tan^2(x)", "\\sec^2(x)"],
        ["\\cot^2(x)+1", "\\csc^2(x)"],
        ["\\lim_{x \\to 0} \\frac{\\sin(小数)}{同样的小数}=?", "1"],
        ["\\lim_{x \\to 0} \\frac{\\tan(小数)}{同样的小数}=?", "1"],
        ["\\lim_{x \\to 0} \\cos(小数)=?", "1"],
        ["\\lim_{x \\to 0} \\frac{1-\\cos(x)}{x}", "0"],
        ["\\lim_{x \\to \\infty} \\frac{\\sin(任何东西)}{x^a}(a>0)=?", "0"],
        ["\\frac{d}{dx}\\sin(x)=?", "\\cos(x)"],
        ["\\frac{d}{dx}\\cos(x)=?", "-\\sin(x)"],
        ["\\frac{d}{dx}\\tan(x)=?", "\\sec^2(x)"],
        ["\\frac{d}{dx}\\cot(x)=?", "-\\csc^2(x)"],
        ["\\frac{d}{dx}\\sec(x)=?", "\\sec(x)\\tan(x)"],
        ["\\frac{d}{dx}\\csc(x)=?", "-\\csc(x)\\cot(x)"],
        ["\\displaylines{h(x)=f(x)g(x) \\\\ h'(x) = ?}\n", "f'(x)g(x)+f(x)g'(x)"],
        ["\\displaylines{h(x)=\\frac{f(x)}{g(x)} \\\\ h'(x) = ?}\n", "\\frac{f'(x)g(x)-f(x)g'(x)}{g^2(x)}"],
        ["\\displaylines{h(x)=f[g(x)] \\\\ h'(x) = ?}\n", "f'[g(x)]g'(x)"],
    ]
}
