export default {
    name: "log",
    cards: [
        ["b^xb^y=?", "b^{(x+y)}"],
        ["\\frac{b^x}{b^y}=?", "b^{(x-y)}"],
        ["(b^x)^y=?", "b^{xy}"],
        ["b^{\\log_{b} (y)}=?", "y"],
        ["\\log_{b} (b^x)=?", "x"],
        ["\\log_{b} (1)=?", "0"],
        ["\\log_{b} (b)=?", "1"],
        ["\\log_{b} (xy)=?", "\\log_{b} (x) + \\log_{b} (y)"],
        ["\\log_{b} (\\frac{x}{y})=?", "\\log_{b} (x) - \\log_{b} (y)"],
        ["\\log_{b} (x^y)=?", "y\\log_{b} (x)"],
        ["换成以c为底：\\log_{b} (x)", "\\frac{\\log_{c} (x)}{\\log_{c} (b)}"],
        ["\\lim_{n \\to \\infty}{(1+\\frac{x}{n})^n}", "e^x"],
        ["\\lim_{h \\to 0}{(1+xh)^{\\frac{1}{h}}}", "e^x"],
        ["\\lim_{n \\to \\infty}{(1+\\frac{1}{n})^{n}}", "e"],
        ["\\lim_{h \\to 0}{(1+h)^{\\frac{1}{h}}}", "e"],
        ["\\frac{d}{dx} \\ln{(x)}", "\\frac{1}{x}"],
        ["\\frac{d}{dx} \\log_{b}{(x)}", "\\frac{1}{x\\ln{(b)}}"],
        ["\\frac{d}{dx} (b^x)", "b^x\\ln{(b)}"],
        ["\\frac{d}{dx} (e^x)", "e^x"],
        ["\\lim_{h \\to 0}{\\frac{e^h-1}{h}}", "1"],
        ["\\lim_{h \\to 0}{\\frac{\\ln{(1+h)}}{h}}", "1"],
        ["\\lim_{x \\to -\\infty}{e^x}", "0"],
        ["\\lim_{x \\to \\infty}{e^x}", "\\infty"],
        [ "\\lim_{x \\to \\infty}{r^x}", "\\lim_{x \\to \\infty}{r^x} =\\begin{cases}" +
        "\\infty &\\text{if r>1} \\\\ 1 &\\text{if r=1} \\\\ 0 &\\text{if 0 $\\le$ r<1}\\end{cases}"],
        ["\\lim_{x \\to \\infty}{\\frac{x^n}{e^x}}=0 代表什么?", "指数函数增长迅速"],
        ["\\lim_{x \\to \\infty}{\\frac{\\ln{x}}{x^a}}(a>0)", "0"],
        ["\\lim_{x \\to 0^+}{x^a\\ln{(x)}},(a>0)", "0(对数函数增长缓慢)"],
        ["\\frac{dy}{dx}=ky意味着什么?", "y=Ae^{kx}, A为常数"],
    ]
}
